SET NAMES utf8;
INSERT INTO property VALUES (2, '2894', 'ka','prefLabel','სოციალური ასპექტები, გარემოსდაცვითი პოლიტიკის ზომები',0);
INSERT INTO property VALUES (2, '4044', 'ka','prefLabel','ადამიანური საქმიანობა და მისი შედეგი, ზემოქმედება გარემოზე',0);
INSERT INTO property VALUES (2, '5306', 'ka','prefLabel','დამხმარე სიები',0);
INSERT INTO property VALUES (2, '5499', 'ka','prefLabel','ბუნებრივი გარემო, ადამიანის სამოსახლო გარემო',0);
INSERT INTO property VALUES (3, '10111', 'ka','prefLabel','გარემო (ბუნებრივი გარემო, ადამიანის სამოსახლო გარემო)',0);
INSERT INTO property VALUES (3, '10112', 'ka','prefLabel','ნაწარმი, მასალები',0);
INSERT INTO property VALUES (3, '10114', 'ka','prefLabel','ზემოქმედება, გავლენა',0);
INSERT INTO property VALUES (3, '10117', 'ka','prefLabel','საერთო ტერმინები',0);
INSERT INTO property VALUES (3, '10118', 'ka','prefLabel','რესურსები (რესურსების გამოყენება)',0);
INSERT INTO property VALUES (3, '1062', 'ka','prefLabel','ანთროპოსფერო (შექმნილი გარემო, დასახლებები, მიწის დაყოფა)',0);
INSERT INTO property VALUES (3, '13109', 'ka','prefLabel','გარემოსდაცვითი პოლიტიკა',0);
INSERT INTO property VALUES (3, '1349', 'ka','prefLabel','ქიმია, ნივთიერებები,პროცესები',0);
INSERT INTO property VALUES (3, '14979', 'ka','prefLabel','დრო (ქრონოლოგია)',0);
INSERT INTO property VALUES (3, '14980', 'ka','prefLabel','ფუნქციური ტერმინები',0);
INSERT INTO property VALUES (3, '1922', 'ka','prefLabel','ინფორმაცია,განათლება, კულტურა, გარემოსდაცვითი ინფორმირება',0);
INSERT INTO property VALUES (3, '234', 'ka','prefLabel','სოფლის მეურნეობა,სატყეო მეურნეობა, მეცხოველეობა, თევზჭერა',0);
INSERT INTO property VALUES (3, '2504', 'ka','prefLabel','ეკონომიკა, ფინანსები',0);
INSERT INTO property VALUES (3, '2711', 'ka','prefLabel','ენერგია',0);
INSERT INTO property VALUES (3, '3875', 'ka','prefLabel','ჯანდაცვა, კვება',0);
INSERT INTO property VALUES (3, '4125', 'ka','prefLabel','ჰიდროსფერო (მტკნარი წყალი, ზღვის წყალი, წყლები)',0);
INSERT INTO property VALUES (3, '4281', 'ka','prefLabel','მრეწველობა, ხელოსნობა, ტექნოლოგიები, აღჭურვილობა',0);
INSERT INTO property VALUES (3, '4630', 'ka','prefLabel','მიწა (ლანდშაფტი, გეოგრაფია)',0);
INSERT INTO property VALUES (3, '4750', 'ka','prefLabel','კანონმდებლობა,ნორმები, კონვენციები',0);
INSERT INTO property VALUES (3, '4856', 'ka','prefLabel','ლითოსფერო (ნიადაგი, გეოლოგიური პროცესები)',0);
INSERT INTO property VALUES (3, '618', 'ka','prefLabel','ატმოსფერო (ჰაერი, კლიმატი)',0);
INSERT INTO property VALUES (3, '6237', 'ka','prefLabel','ფიზიკური ასპექტები, ხმაური, ვიბრაცია, რადიაცია',0);
INSERT INTO property VALUES (3, '7007', 'ka','prefLabel','დასვენება, ტურიზმი',0);
INSERT INTO property VALUES (3, '7136', 'ka','prefLabel','კვლევა, მეცნიერება',0);
INSERT INTO property VALUES (3, '7243', 'ka','prefLabel','რისკები, უსაფრთხოება',0);
INSERT INTO property VALUES (3, '7779', 'ka','prefLabel','საზოგადოება',0);
INSERT INTO property VALUES (3, '7956', 'ka','prefLabel','კოსმოსი',0);
INSERT INTO property VALUES (3, '8575', 'ka','prefLabel','ვაჭრობა, მომსახურება',0);
INSERT INTO property VALUES (3, '8603', 'ka','prefLabel','მოძრაობა, გადაზიდვები',0);
INSERT INTO property VALUES (3, '893', 'ka','prefLabel','ბიოსფერო (ორგანიზმები, ეკოსისტემები)',0);
INSERT INTO property VALUES (3, '9117', 'ka','prefLabel','ნარჩენები, დამბინძურებლები, დაბინძურება',0);
INSERT INTO property VALUES (3, '96', 'ka','prefLabel','ადმინისტრაცია, მართვა,პოლიტიკა, პოლიტიკური პროცესები, დაწესებულებები, დაგეგმვა',0);
INSERT INTO property VALUES (4, '1', 'ka','prefLabel','ადმინისტრაცია',0);
INSERT INTO property VALUES (4, '10', 'ka','prefLabel','ენერგია',0);
INSERT INTO property VALUES (4, '11', 'ka','prefLabel','გარემოსდაცვითი პოლიტიკა',0);
INSERT INTO property VALUES (4, '12', 'ka','prefLabel','თევზჭერა',0);
INSERT INTO property VALUES (4, '13', 'ka','prefLabel','საკვები, სასმელი წყალი',0);
INSERT INTO property VALUES (4, '14', 'ka','prefLabel','სატყეო მეურნეობა',0);
INSERT INTO property VALUES (4, '15', 'ka','prefLabel','საერთო',0);
INSERT INTO property VALUES (4, '16', 'ka','prefLabel','გეოგრაფია',0);
INSERT INTO property VALUES (4, '17', 'ka','prefLabel','ადამიანის ჯანმრთელობა',0);
INSERT INTO property VALUES (4, '18', 'ka','prefLabel','მეცხოველეობა',0);
INSERT INTO property VALUES (4, '19', 'ka','prefLabel','მრეწველობა',0);
INSERT INTO property VALUES (4, '2', 'ka','prefLabel','სოფლის მეურნეობა',0);
INSERT INTO property VALUES (4, '20', 'ka','prefLabel','ინფორმაცია',0);
INSERT INTO property VALUES (4, '21', 'ka','prefLabel','კანონმდებლობა',0);
INSERT INTO property VALUES (4, '22', 'ka','prefLabel','სამხედრო ასპექტები',0);
INSERT INTO property VALUES (4, '23', 'ka','prefLabel','ბუნებრივი ზონები, ლანდშაფტი, ეკოსისტემები',0);
INSERT INTO property VALUES (4, '24', 'ka','prefLabel','ხმაური, ვიბრაციები',0);
INSERT INTO property VALUES (4, '25', 'ka','prefLabel','ფიზიკა',0);
INSERT INTO property VALUES (4, '26', 'ka','prefLabel','დაბინძურება',0);
INSERT INTO property VALUES (4, '27', 'ka','prefLabel','მასალები',0);
INSERT INTO property VALUES (4, '28', 'ka','prefLabel','რადიაციები',0);
INSERT INTO property VALUES (4, '29', 'ka','prefLabel','ტურიზმი',0);
INSERT INTO property VALUES (4, '3', 'ka','prefLabel','ჰაერი',0);
INSERT INTO property VALUES (4, '30', 'ka','prefLabel','კვლევა, მეცნიერება',0);
INSERT INTO property VALUES (4, '31', 'ka','prefLabel','რესურსები',0);
INSERT INTO property VALUES (4, '32', 'ka','prefLabel','კატასტროფები, ავარიები, რისკი',0);
INSERT INTO property VALUES (4, '33', 'ka','prefLabel','ვაჭრობა, მომსახურება',0);
INSERT INTO property VALUES (4, '34', 'ka','prefLabel','სოციალური  ასპექტები, მოსახლეობა',0);
INSERT INTO property VALUES (4, '35', 'ka','prefLabel','ნიადაგი',0);
INSERT INTO property VALUES (4, '36', 'ka','prefLabel','კოსმოსი',0);
INSERT INTO property VALUES (4, '37', 'ka','prefLabel','ტრანსპორტი',0);
INSERT INTO property VALUES (4, '38', 'ka','prefLabel','ქალაქური გარემო, ურბანული სტრესები',0);
INSERT INTO property VALUES (4, '39', 'ka','prefLabel','ნარჩენები',0);
INSERT INTO property VALUES (4, '4', 'ka','prefLabel','ბიოლოგია',0);
INSERT INTO property VALUES (4, '40', 'ka','prefLabel','წყალი',0);
INSERT INTO property VALUES (4, '5', 'ka','prefLabel','მშენებლობა',0);
INSERT INTO property VALUES (4, '6', 'ka','prefLabel','ქიმია',0);
INSERT INTO property VALUES (4, '7', 'ka','prefLabel','კლიმატი',0);
INSERT INTO property VALUES (4, '8', 'ka','prefLabel','ბუნებრივი დინამიკა',0);
INSERT INTO property VALUES (4, '9', 'ka','prefLabel','ეკონომიკა',0);
