      INSERT INTO property VALUES (5,  5 ,"ca","prefLabel", "Adreces",0);
      INSERT INTO property VALUES (5,  4 ,"ca","prefLabel", "Unitats administratives",0);
      INSERT INTO property VALUES (5, 22 ,"ca","prefLabel", "Instal·lacions agrícoles i d'aqüicultura",0);
      INSERT INTO property VALUES (5, 24 ,"ca","prefLabel", "Zones subjectes a ordenació, a restriccions o reglamentacions i unitats de notificació.",0);
      INSERT INTO property VALUES (5, 26 ,"ca","prefLabel", "Condicions atmosfèriques",0);
      INSERT INTO property VALUES (5, 30 ,"ca","prefLabel", "Regions biogeogràfiques",0);
      INSERT INTO property VALUES (5, 15 ,"ca","prefLabel", "Edificis",0);
      INSERT INTO property VALUES (5,  6 ,"ca","prefLabel", "Parcel·les cadastrals",0);
      INSERT INTO property VALUES (5,  1 ,"ca","prefLabel", "Sistemes de coordenades de referència",0);
      INSERT INTO property VALUES (5, 10 ,"ca","prefLabel", "Elevacions",0);
      INSERT INTO property VALUES (5, 33 ,"ca","prefLabel", "Recursos energètics",0);
      INSERT INTO property VALUES (5, 20 ,"ca","prefLabel", "Instal·lacions d'observació del medi ambient",0);
      INSERT INTO property VALUES (5,  2 ,"ca","prefLabel", "Sistema de quadrícules geogràfiques",0);
      INSERT INTO property VALUES (5,  3 ,"ca","prefLabel", "Noms geogràfics",0);
      INSERT INTO property VALUES (5, 13 ,"ca","prefLabel", "Geologia",0);
      INSERT INTO property VALUES (5, 31 ,"ca","prefLabel", "Hàbitats i biòtops",0);
      INSERT INTO property VALUES (5, 18 ,"ca","prefLabel", "Salut i seguretat humanes",0);
      INSERT INTO property VALUES (5,  8 ,"ca","prefLabel", "Hidrografia",0);
      INSERT INTO property VALUES (5, 11 ,"ca","prefLabel", "Coberta terrestre",0);
      INSERT INTO property VALUES (5, 17 ,"ca","prefLabel", "Ús del sòl",0);
      INSERT INTO property VALUES (5, 27 ,"ca","prefLabel", "Aspectes geogràfics de caràcter meteorològic",0);
      INSERT INTO property VALUES (5, 34 ,"ca","prefLabel", "Recursos minerals",0);
      INSERT INTO property VALUES (5, 25 ,"ca","prefLabel", "Zones de riscos naturals",0);
      INSERT INTO property VALUES (5, 28 ,"ca","prefLabel", "Aspectes geogràfics oceanogràfics",0);
      INSERT INTO property VALUES (5, 12 ,"ca","prefLabel", "Ortoimatges",0);
      INSERT INTO property VALUES (5, 23 ,"ca","prefLabel", "Distribució de la població - demografia",0);
      INSERT INTO property VALUES (5, 21 ,"ca","prefLabel", "Instal·lacions de producció i industrials",0);
      INSERT INTO property VALUES (5,  9 ,"ca","prefLabel", "Llocs protegits",0);
      INSERT INTO property VALUES (5, 29 ,"ca","prefLabel", "Regions marines",0);
      INSERT INTO property VALUES (5, 16 ,"ca","prefLabel", "Sòl",0);
      INSERT INTO property VALUES (5, 32 ,"ca","prefLabel", "Distribució de les espècies",0);
      INSERT INTO property VALUES (5, 14 ,"ca","prefLabel", "Unitats estadístiques",0);
      INSERT INTO property VALUES (5,  7 ,"ca","prefLabel", "Xarxes de transport",0);
      INSERT INTO property VALUES (5, 19 ,"ca","prefLabel", "Serveis d'utilitat pública i estatals",0);
