SET NAMES utf8;
INSERT INTO property VALUES (2, '2894', 'hy','prefLabel','ՍՈՑԻԱԼԱԿԱՆ ԲՆԱԳԱՎԱՌՆԵՐ, ԲԱՆԱՊԱՀՊԱՆԱԿԱՆ ՔԱՂԱՔԱԿԱՆՈՒԹՅԱՆ ՄԻՋՈՑՆԵՐ',0);
INSERT INTO property VALUES (2, '4044', 'hy','prefLabel','ՄԱՐԴՈՒ ԳՈՐԾՈՒՆԵՈՒԹՅՈՒՆԸ ԵՎ ԴՐԱ ԱՐԴՅՈՒՆՔՆԵՐԸ, ՇՐՋԱԿԱ ՄԻՋԱՎԱՅՐԻ ՎՐԱ ԱԶԴԵՑՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (2, '5306', 'hy','prefLabel','ՕԺԱՆԴԱԿ ՏԵՐՄԻՆՆԵՐ',0);
INSERT INTO property VALUES (2, '5499', 'hy','prefLabel','ԲՆԱԿԱՆ ՄԻՋԱՎԱՅՐ, ՄԱՐԴՈՒՆ ՇՐՋԱՊԱՏՈՂ ՄԻՋԱՎԱՅՐ',0);
INSERT INTO property VALUES (3, '10111', 'hy','prefLabel','ՇՐՋԱԿԱ ՄԻՋԱՎԱՅՐ (բնական միրավայր, մարդուն շրջապատող միջավայր)',0);
INSERT INTO property VALUES (3, '10112', 'hy','prefLabel','ԱՐՏԱԴՐԱՆՔ, ՆՅՈՒԹԵՐ',0);
INSERT INTO property VALUES (3, '10114', 'hy','prefLabel','ՀԵՏԵՎԱՆՔՆԵՐ, ԱԶԴԵՑՈՒԹՅՈՒՆՆԵՐ',0);
INSERT INTO property VALUES (3, '10117', 'hy','prefLabel','ԸՆԴՀԱՆՈՒՐ ՏԵՐՄԻՆՆԵՐ',0);
INSERT INTO property VALUES (3, '10118', 'hy','prefLabel','ՌԵՍՈՒՐՍՆԵՐ (ռեսուրսների օգտագործում)',0);
INSERT INTO property VALUES (3, '1062', 'hy','prefLabel','ՄԱՐԴԱԾԻՆ ՄԻՋԱՎԱՅՐ/ ԱՆԹՐՊՈՍՖԵՐԱ (մարդու կողմից ստեղծված շրջակա միջավայր, բնակավայրեր, հողերի տարածքային պլանավորում)',0);
INSERT INTO property VALUES (3, '13109', 'hy','prefLabel','ԲՆԱՊԱՀՊԱՆԱԿԱՆ ՔԱՂԱՔԱԿԱՆՈՒԹՅՈՒՆ (ԷԿՈԼՈԳԻԱԿԱՆ ՔԱՂԱՔԱԿԱՆՈՒԹՅՈՒՆ)',0);
INSERT INTO property VALUES (3, '1349', 'hy','prefLabel','ՔԻՄԻԱ, ՆՅՈՒԹԵՐ, ՊՐՈՑԵՍՆԵՐ',0);
INSERT INTO property VALUES (3, '14979', 'hy','prefLabel','ԺԱՄԱՆԱԿ (ժամանակագրություն)',0);
INSERT INTO property VALUES (3, '14980', 'hy','prefLabel','ԳՈՐԾԱՌՆԱԿԱՆ  (ՖՈՒՆԿՑԻՈՆԱԼ) ՏԵՐՄԻՆՆԵՐ',0);
INSERT INTO property VALUES (3, '1922', 'hy','prefLabel','ՏԵՂԵԿԱՏՎՈՒԹՅՈՒՆ, ԿՐԹՈՒԹՅՈՒՆ, ՄՇԱԿՈՒՅԹ, ԲՆԱՊԱՀՊԱՆԱԿԱՆ ԻՐԱԶԵԿՎԱԾՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (3, '234', 'hy','prefLabel','ԳՅՈՒՂԱՏՆՏԵՍՈՒԹՅՈՒՆ, ԱՆՏԱՌԱՅԻՆ ՏՆՏԵՍՈՒԹՅՈՒՆ, ԱՆԱՍՆԱԲՈՒԾՈՒԹՅՈՒՆ, ՁԿՆԱԲՈՒԾՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (3, '2504', 'hy','prefLabel','ԷԿՈՆՈՄԻԿԱ, ՖԻՆԱՆՍՆԵՐ',0);
INSERT INTO property VALUES (3, '2711', 'hy','prefLabel','ԷՆԵՐԳԻԱ',0);
INSERT INTO property VALUES (3, '3875', 'hy','prefLabel','ԱՌՈՂՋՈՒԹՅՈՒՆ, ՍՆՈՒՆԴ',0);
INSERT INTO property VALUES (3, '4125', 'hy','prefLabel','ՋՐՈԼՈՐՏ/ ՀԻԴՐՈՍՖԵՐԱ ( քաղցրահամ ջուր, ծովի ջուր, ջրային ռեսուրսներ)',0);
INSERT INTO property VALUES (3, '4281', 'hy','prefLabel','ԱՐԴՅՈՒՆԱԲԵՐՈՒԹՅՈՒՆ, ԱՐՀԵՍՏԱԳՈՐԾՈՒԹՅՈՒՆ. ՏԵԽՆՈԼՈԳԻԱ, ՍԱՐՔԱՎՈՐՈՒՄՆԵՐ',0);
INSERT INTO property VALUES (3, '4630', 'hy','prefLabel','ՀՈՂ (լանդշաֆտ, աշխարհագրություն)',0);
INSERT INTO property VALUES (3, '4750', 'hy','prefLabel','ՕՐԵՆՍԴՐՈՒԹՅՈՒՆ, ՆՈՐՄԵՐ, ԿՈՆՎԵՆՑԻԱՆԵՐ',0);
INSERT INTO property VALUES (3, '4856', 'hy','prefLabel','ԼԻԹՈՍՖԵՐԱ (հող, երկրաբանական պրոցեսները)',0);
INSERT INTO property VALUES (3, '618', 'hy','prefLabel','ՄԹՆՈԼՈՐՏ/ ԱՏՄՈՍՖԵՐԱ (օդ, կլիմա)',0);
INSERT INTO property VALUES (3, '6237', 'hy','prefLabel','ՖԻԶԻԿԱԿԱՆ ՆԵՐԳՈՐԾՈՒԹՅՈՒՆՆԵՐԻ ԲՆԱԳԱՎԱՌՆԵՐ` ԱՂՄՈՒԿ, ԹՐԹՌԱՆՔ, ՃԱՌԱԳԱՅԹՈՒՄ',0);
INSERT INTO property VALUES (3, '7007', 'hy','prefLabel','ՌԵԿՐԵԱՑԻԱ, ՏՈՒՐԻԶՄ',0);
INSERT INTO property VALUES (3, '7136', 'hy','prefLabel','ՀԵՏԱԶՈՏՈՒԹՅՈՒՆՆԵՐ, ԳԻՏՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (3, '7243', 'hy','prefLabel','ՌԻՍԿԵՐ, ԱՆՎՏԱՆԳՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (3, '7779', 'hy','prefLabel','ՀԱՍԱՐԱԿՈՒԹՅՈՒՆ',0);
INSERT INTO property VALUES (3, '7956', 'hy','prefLabel','ՏԻԵԶԵՐՔ',0);
INSERT INTO property VALUES (3, '8575', 'hy','prefLabel','ԱՌԵՎՏՈՒՐ,  ԾԱՌԱՅՈՒԹՅՈՒՆՆԵՐ',0);
INSERT INTO property VALUES (3, '8603', 'hy','prefLabel','ՃԱՆԱՊԱՐՀԱՅԻՆ ԵՐԹԵՎԵԿՈՒԹՅՈՒՆ, ՏՐԱՆՍՊՈՐՏ',0);
INSERT INTO property VALUES (3, '893', 'hy','prefLabel','ԿԵՆՍՈԼՈՐՏ/ ԲԻՈՍՖԵՐԱ (օրգանիզմներ, էկոհամակարգեր)',0);
INSERT INTO property VALUES (3, '9117', 'hy','prefLabel','ԹԱՓՈՆՆԵՐ, ԱՂՏՈՏԻՉՆԵՐ, ԱՂՏՈՏՈՒՄ',0);
INSERT INTO property VALUES (3, '96', 'hy','prefLabel','ՎԱՐՉԱԿԱԶՄ, ԿԱՌԱՎԱՐՈՒՄ, ՔԱՂԱՔԱԿԱՆՈՒԹՅՈՒՆ, ՔԱՂԱՔԱԿԱՆ ԿՅԱՆՔ, ՄԱՐՄԻՆՆԵՐ, ՊԼԱՆԱՎՈՐՈՒՄ',0);
INSERT INTO property VALUES (4, '1', 'hy','prefLabel','վարչակազմ',0);
INSERT INTO property VALUES (4, '10', 'hy','prefLabel','էներգիա',0);
INSERT INTO property VALUES (4, '11', 'hy','prefLabel','էկոլոգիական քաղաքականություն',0);
INSERT INTO property VALUES (4, '12', 'hy','prefLabel','ձկնորսություն',0);
INSERT INTO property VALUES (4, '13', 'hy','prefLabel','սննդամթերք, խմելու ջուր',0);
INSERT INTO property VALUES (4, '14', 'hy','prefLabel','անտառային տնտեսություն',0);
INSERT INTO property VALUES (4, '15', 'hy','prefLabel','ընդհանուր',0);
INSERT INTO property VALUES (4, '16', 'hy','prefLabel','աշխարհագրություն',0);
INSERT INTO property VALUES (4, '17', 'hy','prefLabel','մարդու առողջություն',0);
INSERT INTO property VALUES (4, '18', 'hy','prefLabel','անասնաբուծություն',0);
INSERT INTO property VALUES (4, '19', 'hy','prefLabel','արդյունաբերություն',0);
INSERT INTO property VALUES (4, '2', 'hy','prefLabel','գյուղատնտեսություն',0);
INSERT INTO property VALUES (4, '20', 'hy','prefLabel','տեղեկատվություն',0);
INSERT INTO property VALUES (4, '21', 'hy','prefLabel','օրենսդրություն',0);
INSERT INTO property VALUES (4, '22', 'hy','prefLabel','ռազմական բնագավառներ',0);
INSERT INTO property VALUES (4, '23', 'hy','prefLabel','բնական տարածքներ, լանդշաֆտ, էկոհամակարգեր',0);
INSERT INTO property VALUES (4, '24', 'hy','prefLabel','աղմուկ, թրթռանք',0);
INSERT INTO property VALUES (4, '25', 'hy','prefLabel','ֆիզիկա',0);
INSERT INTO property VALUES (4, '26', 'hy','prefLabel','աղտոտում',0);
INSERT INTO property VALUES (4, '27', 'hy','prefLabel','նյութեր',0);
INSERT INTO property VALUES (4, '28', 'hy','prefLabel','ճառագայթում',0);
INSERT INTO property VALUES (4, '29', 'hy','prefLabel','տուրիզմ',0);
INSERT INTO property VALUES (4, '3', 'hy','prefLabel','մթնոլորտ',0);
INSERT INTO property VALUES (4, '30', 'hy','prefLabel','հետազոտություններ',0);
INSERT INTO property VALUES (4, '31', 'hy','prefLabel','ռեսուրսներ',0);
INSERT INTO property VALUES (4, '32', 'hy','prefLabel','աղետներ, վթարներ, ռիսկեր',0);
INSERT INTO property VALUES (4, '33', 'hy','prefLabel','առևտուր, ծառայություններ',0);
INSERT INTO property VALUES (4, '34', 'hy','prefLabel','սոցիալական բնագավառներ, բնակչություն',0);
INSERT INTO property VALUES (4, '35', 'hy','prefLabel','հող',0);
INSERT INTO property VALUES (4, '36', 'hy','prefLabel','տիեզերք',0);
INSERT INTO property VALUES (4, '37', 'hy','prefLabel','տրանսպորտ',0);
INSERT INTO property VALUES (4, '38', 'hy','prefLabel','քաղաքային շրջակա միջավայր, քաղաքային միջավայրի  անբարենպաստ գործոններ',0);
INSERT INTO property VALUES (4, '39', 'hy','prefLabel','թափոններ',0);
INSERT INTO property VALUES (4, '4', 'hy','prefLabel','կենսաբանություն',0);
INSERT INTO property VALUES (4, '40', 'hy','prefLabel','ջուր',0);
INSERT INTO property VALUES (4, '5', 'hy','prefLabel','շենք, շինություն',0);
INSERT INTO property VALUES (4, '6', 'hy','prefLabel','քիմիա',0);
INSERT INTO property VALUES (4, '7', 'hy','prefLabel','կլիմա',0);
INSERT INTO property VALUES (4, '8', 'hy','prefLabel','բնական ընթացաշարժ (դինամիկա)',0);
INSERT INTO property VALUES (4, '9', 'hy','prefLabel','էկոնոմիկա',0);
