UPDATE `theme` SET description="администрация" WHERE langcode='ru' and id_theme=1;
UPDATE `theme` SET description="сельское хозяйство" WHERE langcode='ru' and id_theme=2;
UPDATE `theme` SET description="воздух" WHERE langcode='ru' and id_theme=3;
UPDATE `theme` SET description="биология" WHERE langcode='ru' and id_theme=4;
UPDATE `theme` SET description="строительство" WHERE langcode='ru' and id_theme=5;
UPDATE `theme` SET description="химия" WHERE langcode='ru' and id_theme=6;
UPDATE `theme` SET description="климат" WHERE langcode='ru' and id_theme=7;
UPDATE `theme` SET description="природная динамика" WHERE langcode='ru' and id_theme=8;
UPDATE `theme` SET description="экономика" WHERE langcode='ru' and id_theme=9;
UPDATE `theme` SET description="энергия" WHERE langcode='ru' and id_theme=10;
UPDATE `theme` SET description="экологическая политика" WHERE langcode='ru' and id_theme=11;
UPDATE `theme` SET description="рыболовство" WHERE langcode='ru' and id_theme=12;
UPDATE `theme` SET description="продукты питания, питьевая вода" WHERE langcode='ru' and id_theme=13;
UPDATE `theme` SET description="лесное хозяйство" WHERE langcode='ru' and id_theme=14;
UPDATE `theme` SET description="общее" WHERE langcode='ru' and id_theme=15;
UPDATE `theme` SET description="география" WHERE langcode='ru' and id_theme=16;
UPDATE `theme` SET description="здоровье человека" WHERE langcode='ru' and id_theme=17;
UPDATE `theme` SET description="животноводство" WHERE langcode='ru' and id_theme=18;
UPDATE `theme` SET description="промышленность" WHERE langcode='ru' and id_theme=19;
UPDATE `theme` SET description="информация" WHERE langcode='ru' and id_theme=20;
UPDATE `theme` SET description="законодательство" WHERE langcode='ru' and id_theme=21;
UPDATE `theme` SET description="военные аспекты" WHERE langcode='ru' and id_theme=22;
UPDATE `theme` SET description="природные зоны, ландшафт, экосистемы" WHERE langcode='ru' and id_theme=23;
UPDATE `theme` SET description="шум, вибрация" WHERE langcode='ru' and id_theme=24;
UPDATE `theme` SET description="физика" WHERE langcode='ru' and id_theme=25;
UPDATE `theme` SET description="загрязнение" WHERE langcode='ru' and id_theme=26;
UPDATE `theme` SET description="материалы" WHERE langcode='ru' and id_theme=27;
UPDATE `theme` SET description="излучение" WHERE langcode='ru' and id_theme=28;
UPDATE `theme` SET description="туризм" WHERE langcode='ru' and id_theme=29;
UPDATE `theme` SET description="исследования" WHERE langcode='ru' and id_theme=30;
UPDATE `theme` SET description="ресурсы" WHERE langcode='ru' and id_theme=31;
UPDATE `theme` SET description="бедствия, аварии, риск" WHERE langcode='ru' and id_theme=32;
UPDATE `theme` SET description="торговля, услуги" WHERE langcode='ru' and id_theme=33;
UPDATE `theme` SET description="социальные аспекты, население" WHERE langcode='ru' and id_theme=34;
UPDATE `theme` SET description="почва" WHERE langcode='ru' and id_theme=35;
UPDATE `theme` SET description="космос" WHERE langcode='ru' and id_theme=36;
UPDATE `theme` SET description="транспорт" WHERE langcode='ru' and id_theme=37;
UPDATE `theme` SET description="городская среда, неблагоприятные факторы в условиях города" WHERE langcode='ru' and id_theme=38;
UPDATE `theme` SET description="отходы" WHERE langcode='ru' and id_theme=39;
UPDATE `theme` SET description="вода" WHERE langcode='ru' and id_theme=40;