UPDATE `concept_group` SET description="АДМИНИСТРАЦИЯ, УПРАВЛЕНИЕ, ПОЛИТИКА, ОРГАНЫ, ПЛАНИРОВАНИЕ" WHERE id_group=96 and langcode='ru';
UPDATE `concept_group` SET description="СЕЛЬСКОЕ ХОЗЯЙСТВО, ЛЕСНОЕ ХОЗЯЙСТВО, ЖИВОТНОВОДСТВО, РЫБНОЕ ХОЗЯЙСТВО" WHERE id_group=234 and langcode='ru';
UPDATE `concept_group` SET description="АТМОСФЕРА (воздух, климат)" WHERE id_group=618 and langcode='ru';
UPDATE `concept_group` SET description="БИОСФЕРА (организмы, экосистемы)" WHERE id_group=893 and langcode='ru';
UPDATE `concept_group` SET description="АНТРОПОСФЕРА (созданная среда, населенные пункты, региональное планирование)" WHERE id_group=1062 and langcode='ru';
UPDATE `concept_group` SET description="ХИМИЯ, ВЕЩЕСТВА, ПРОЦЕССЫ" WHERE id_group=1349 and langcode='ru';
UPDATE `concept_group` SET description="ИНФОРМАЦИЯ, ОБРАЗОВАНИЕ, КУЛЬТУРА, ИНФОРМИРОВАННОСТЬ ОБ ОКРУЖАЮЩЕЙ СРЕДЕ" WHERE id_group=1922 and langcode='ru';
UPDATE `concept_group` SET description="ЭКОНОМИКА, ФИНАНСЫ" WHERE id_group=2504 and langcode='ru';
UPDATE `concept_group` SET description="ЭНЕРГИЯ" WHERE id_group=2711 and langcode='ru';
UPDATE `concept_group` SET description="СОЦИАЛЬНЫЕ АСПЕКТЫ, МЕРЫ ЭКОЛОГИЧЕСКОЙ ПОЛИТИКИ" WHERE id_group=2894 and langcode='ru';
UPDATE `concept_group` SET description="ЗДОРОВЬЕ, ПИТАНИЕ" WHERE id_group=3875 and langcode='ru';
UPDATE `concept_group` SET description="ДЕЯТЕЛЬНОСТЬ ЧЕЛОВЕКА И ЕЕ РЕЗУЛЬТАТЫ, ВОЗДЕЙСТВИЕ НА ОКРУЖАЮЩУЮ СРЕДУ" WHERE id_group=4044 and langcode='ru';
UPDATE `concept_group` SET description="ГИДРОСФЕРА (пресная вода, морская вода, водные ресурсы)" WHERE id_group=4125 and langcode='ru';
UPDATE `concept_group` SET description="ПРОМЫШЛЕННОСТЬ, РЕМЕСЛА, ТЕХНОЛОГИИ, ОБОРУДОВАНИЕ" WHERE id_group=4281 and langcode='ru';
UPDATE `concept_group` SET description="ЗЕМЛЯ (ландшафт, география)" WHERE id_group=4630 and langcode='ru';
UPDATE `concept_group` SET description="ЗАКОНОДАТЕЛЬСТВО, НОРМЫ, КОНВЕНЦИИ" WHERE id_group=4750 and langcode='ru';
UPDATE `concept_group` SET description="ЛИТОСФЕРА (почва, геологические процессы)" WHERE id_group=4856 and langcode='ru';
UPDATE `concept_group` SET description="ВСПОМОГАТЕЛЬНЫЕ ТЕРМИНЫ" WHERE id_group=5306 and langcode='ru';
UPDATE `concept_group` SET description="ПРИРОДНАЯ СРЕДА, СРЕДА ОБИТАНИЯ ЧЕЛОВЕКА" WHERE id_group=5499 and langcode='ru';
UPDATE `concept_group` SET description="ФИЗИЧЕСКИЕ АСПЕКТЫ, ШУМ, ВИБРАЦИЯ, РАДИАЦИЯ" WHERE id_group=6237 and langcode='ru';
UPDATE `concept_group` SET description="ОТДЫХ, ТУРИЗМ" WHERE id_group=7007 and langcode='ru';
UPDATE `concept_group` SET description="ИССЛЕДОВАНИЯ, НАУКА" WHERE id_group=7136 and langcode='ru';
UPDATE `concept_group` SET description="РИСКИ, БЕЗОПАСНОСТЬ" WHERE id_group=7243 and langcode='ru';
UPDATE `concept_group` SET description="ОБЩЕСТВО" WHERE id_group=7779 and langcode='ru';
UPDATE `concept_group` SET description="КОСМОС" WHERE id_group=7956 and langcode='ru';
UPDATE `concept_group` SET description="ТОРГОВЛЯ, УСЛУГИ" WHERE id_group=8575 and langcode='ru';
UPDATE `concept_group` SET description="ДОРОЖНОЕ ДВИЖЕНИЕ, ТРАНСПОРТ" WHERE id_group=8603 and langcode='ru';
UPDATE `concept_group` SET description="ОТХОДЫ, ЗАГРЯЗНЯЮЩИЕ ВЕЩЕСТВА, ЗАГРЯЗНЕНИЕ" WHERE id_group=9117 and langcode='ru';
UPDATE `concept_group` SET description="ОКРУЖАЮЩАЯ СРЕДА (природная среда, среда обитания человека)" WHERE id_group=10111 and langcode='ru';
UPDATE `concept_group` SET description="ПРОДУКТЫ, МАТЕРИАЛЫ" WHERE id_group=10112 and langcode='ru';
UPDATE `concept_group` SET description="ВОЗДЕЙСТВИЕ, ВЛИЯНИЕ" WHERE id_group=10114 and langcode='ru';
UPDATE `concept_group` SET description="ОБЩИЕ ТЕРМИНЫ" WHERE id_group=10117 and langcode='ru';
UPDATE `concept_group` SET description="РЕСУРСЫ (использование ресурсов)" WHERE id_group=10118 and langcode='ru';
UPDATE `concept_group` SET description="ПОЛИТИКА В ОБЛАСТИ ОХРАНЫ ОКРУЖАЮЩЕЙ СРЕДЫ" WHERE id_group=13109 and langcode='ru';
UPDATE `concept_group` SET description="ВРЕМЯ (хронология)" WHERE id_group=14979 and langcode='ru';
UPDATE `concept_group` SET description="ФУНКЦИОНАЛЬНЫЕ ТЕРМИНЫ" WHERE id_group=14980 and langcode='ru';