-- #TODO: on 'Insert new concepts' all the concepts are associated to 'NOT ACCEPTED TERMS' group,
--        also all the new concepts have no relations among concepts defined (e.g. Narrower, Broader etc)
--        also these association nor gruops. Some of the new concepts have the definitions only in RU but not in EN.
--        Many of the new EN definitions are trunkated in the Excel file.

-- # Montreal protocol was found here:
-- There are many other definitions available, referring to ETC/CDS
-- http://iaspub.epa.gov/trs/trs_proc_qry.alphabet?p_term_nm=ALL&p_reg_auth_id=1&p_data_id=11652&p_version=1

-- geographic distribution of resources found here:
-- http://iaspub.epa.gov/trs/trs_proc_qry.alphabet?p_term_nm=G

-- Insert new concepts
INSERT INTO `concept`  VALUES  (70, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (174, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (408, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (711, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (713, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (734, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (780, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (958, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (983, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1022, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1140, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1197, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1285, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1599, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (1733, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2019, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2049, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2120, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2154, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2205, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2281, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (2906, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3004, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3145, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3146, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3150, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3642, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3643, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3883, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (3927, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (4142, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (4168, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (4949, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (4978, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5074, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5109, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5114, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5118, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5275, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5324, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5533, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5562, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5779, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5947, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5961, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (5970, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6042, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6089, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6303, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6322, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6582, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6598, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6648, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6653, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6665, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6707, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6748, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (6995, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7098, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7109, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7158, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7432, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7463, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7589, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7704, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (7971, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (8066, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (8245, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (8423, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (8457, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (8890, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (9037, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (9038, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (9104, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (10091, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (10252, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (10253, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (10799, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (10800, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11009, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11059, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11121, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11380, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11381, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11382, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11416, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11417, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11520, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11529, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11584, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (11780, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13070, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13108, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13129, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13131, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13578, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13756, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (13983, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (14113, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (14840, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (14841, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (14846, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `concept`  VALUES  (14942, 15028, 'n', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

-- Insert new English terms
INSERT INTO `term` VALUES (70, 'action', 'en');
INSERT INTO `term` VALUES (174, 'Agenda 21', 'en');
INSERT INTO `term` VALUES (408, 'ancient times', 'en');
INSERT INTO `term` VALUES (711, 'balance of nature', 'en');
INSERT INTO `term` VALUES (713, 'balancing (process)', 'en');
INSERT INTO `term` VALUES (734, 'Basel Convention', 'en');
INSERT INTO `term` VALUES (780, 'Bern Convention', 'en');
INSERT INTO `term` VALUES (958, 'Bonn Convention', 'en');
INSERT INTO `term` VALUES (983, 'brackish', 'en');
INSERT INTO `term` VALUES (1022, 'Brussels additional agreement', 'en');
INSERT INTO `term` VALUES (1140, 'cantonal law', 'en');
INSERT INTO `term` VALUES (1197, 'carrier', 'en');
INSERT INTO `term` VALUES (1285, 'change in use', 'en');
INSERT INTO `term` VALUES (1599, 'commissioner for dangerous goods', 'en');
INSERT INTO `term` VALUES (1733, 'consumer', 'en');
INSERT INTO `term` VALUES (2019, 'decrease', 'en');
INSERT INTO `term` VALUES (2049, 'delegation', 'en');
INSERT INTO `term` VALUES (2120, 'destruction', 'en');
INSERT INTO `term` VALUES (2154, 'development', 'en');
INSERT INTO `term` VALUES (2205, 'DIN standard', 'en');
INSERT INTO `term` VALUES (2281, 'doctor', 'en');
INSERT INTO `term` VALUES (2906, 'environmental protection officer', 'en');
INSERT INTO `term` VALUES (3004, 'European Recovery Programme', 'en');
INSERT INTO `term` VALUES (3145, 'federal highway', 'en');
INSERT INTO `term` VALUES (3146, 'Federal Immission Control Act', 'en');
INSERT INTO `term` VALUES (3150, 'feed-in current', 'en');
INSERT INTO `term` VALUES (3642, 'geographic attribute', 'en');
INSERT INTO `term` VALUES (3643, 'geographic distribution of resources', 'en');
INSERT INTO `term` VALUES (3883, 'hearing authority', 'en');
INSERT INTO `term` VALUES (3927, 'Helsinki Convention', 'en');
INSERT INTO `term` VALUES (4142, 'IMCO Conference', 'en');
INSERT INTO `term` VALUES (4168, 'importer', 'en');
INSERT INTO `term` VALUES (4949, 'MAB Programme', 'en');
INSERT INTO `term` VALUES (4978, 'malfunction', 'en');
INSERT INTO `term` VALUES (5074, 'Marpol agreement', 'en');
INSERT INTO `term` VALUES (5109, 'mayor', 'en');
INSERT INTO `term` VALUES (5114, 'medium', 'en');
INSERT INTO `term` VALUES (5118, 'measure', 'en');
INSERT INTO `term` VALUES (5275, 'mineral rock and earth industry', 'en');
INSERT INTO `term` VALUES (5324, 'mobility (physical)', 'en');
INSERT INTO `term` VALUES (5533, 'nature', 'en');
INSERT INTO `term` VALUES (5562, 'neighbouring owner', 'en');
INSERT INTO `term` VALUES (5779, 'observatory (in general)', 'en');
INSERT INTO `term` VALUES (5947, 'Oslo agreement', 'en');
INSERT INTO `term` VALUES (5961, 'overflow (process)', 'en');
INSERT INTO `term` VALUES (5970, 'owner of waste', 'en');
INSERT INTO `term` VALUES (6042, 'Paris Convention', 'en');
INSERT INTO `term` VALUES (6089, 'pedestrian', 'en');
INSERT INTO `term` VALUES (6303, 'plant delegate', 'en');
INSERT INTO `term` VALUES (6322, 'plant size (industry)', 'en');
INSERT INTO `term` VALUES (6582, 'prehistory', 'en');
INSERT INTO `term` VALUES (6598, 'prevention', 'en');
INSERT INTO `term` VALUES (6648, 'procedure', 'en');
INSERT INTO `term` VALUES (6653, 'MSR technique', 'en');
INSERT INTO `term` VALUES (6665, 'production', 'en');
INSERT INTO `term` VALUES (6707, 'programming', 'en');
INSERT INTO `term` VALUES (6748, 'protection', 'en');
INSERT INTO `term` VALUES (6995, 'recovery', 'en');
INSERT INTO `term` VALUES (7098, 'reliability', 'en');
INSERT INTO `term` VALUES (7109, 'renovation', 'en');
INSERT INTO `term` VALUES (7158, 'residue', 'en');
INSERT INTO `term` VALUES (7432, 'sanitary assistance', 'en');
INSERT INTO `term` VALUES (7463, 'scenario', 'en');
INSERT INTO `term` VALUES (7589, 'selectivity', 'en');
INSERT INTO `term` VALUES (7704, 'single European act', 'en');
INSERT INTO `term` VALUES (7971, 'space utilisation', 'en');
INSERT INTO `term` VALUES (8066, 'statement of facts', 'en');
INSERT INTO `term` VALUES (8245, 'sustainability', 'en');
INSERT INTO `term` VALUES (8423, 'textile technology', 'en');
INSERT INTO `term` VALUES (8457, 'thickness of insulating layer', 'en');
INSERT INTO `term` VALUES (8890, 'value', 'en');
INSERT INTO `term` VALUES (9037, 'washing', 'en');
INSERT INTO `term` VALUES (9038, 'Washington species protection convention', 'en');
INSERT INTO `term` VALUES (9104, 'waste producer', 'en');
INSERT INTO `term` VALUES (10091, 'noise impact in daily life', 'en');
INSERT INTO `term` VALUES (10252, 'Rio Conference', 'en');
INSERT INTO `term` VALUES (10253, 'Stockholm Conference', 'en');
INSERT INTO `term` VALUES (10799, 'ecological consultant', 'en');
INSERT INTO `term` VALUES (10800, 'environmental toxicologist', 'en');
INSERT INTO `term` VALUES (11009, 'member of Parliament', 'en');
INSERT INTO `term` VALUES (11059, 'balance of materials', 'en');
INSERT INTO `term` VALUES (11121, 'state of the environment', 'en');
INSERT INTO `term` VALUES (11380, 'Geneva Convention', 'en');
INSERT INTO `term` VALUES (11381, 'Lomé Convention', 'en');
INSERT INTO `term` VALUES (11382, 'Seveso Directive', 'en');
INSERT INTO `term` VALUES (11416, 'Geneva Protocol', 'en');
INSERT INTO `term` VALUES (11417, 'Montreal Protocol', 'en');
INSERT INTO `term` VALUES (11520, 'investigating commissioner', 'en');
INSERT INTO `term` VALUES (11529, 'right of access to administrative documents', 'en');
INSERT INTO `term` VALUES (11584, 'public prosecutor', 'en');
INSERT INTO `term` VALUES (11780, 'cycle (phenomenon)', 'en');
INSERT INTO `term` VALUES (13070, 'alteration', 'en');
INSERT INTO `term` VALUES (13108, 'natural dynamics', 'en');
INSERT INTO `term` VALUES (13129, 'prospective', 'en');
INSERT INTO `term` VALUES (13131, 'hygienist', 'en');
INSERT INTO `term` VALUES (13578, 'migration (in general)', 'en');
INSERT INTO `term` VALUES (13756, 'durability', 'en');
INSERT INTO `term` VALUES (13983, 'feeding current', 'en');
INSERT INTO `term` VALUES (14113, 'Ramsar Convention', 'en');
INSERT INTO `term` VALUES (14840, 'intergovernmental', 'en');
INSERT INTO `term` VALUES (14841, 'governmental', 'en');
INSERT INTO `term` VALUES (14846, 'academic', 'en');
INSERT INTO `term` VALUES (14942, 'industrial or commercial', 'en');

-- Insert new Russian terms
INSERT INTO `term` VALUES (70, 'действие', 'ru');
INSERT INTO `term` VALUES (174, 'Повестка дня на XXI век', 'ru');
INSERT INTO `term` VALUES (408, 'древние времена', 'ru');
INSERT INTO `term` VALUES (711, 'природный баланс', 'ru');
INSERT INTO `term` VALUES (713, 'балансирование (процесс)', 'ru');
INSERT INTO `term` VALUES (734, 'Базельская Конвенция', 'ru');
INSERT INTO `term` VALUES (780, 'Бернская Конвенция', 'ru');
INSERT INTO `term` VALUES (958, 'Боннская Конвенция', 'ru');
INSERT INTO `term` VALUES (983, 'солоноватый', 'ru');
INSERT INTO `term` VALUES (1022, 'Брюссельское дополнительное соглашение', 'ru');
INSERT INTO `term` VALUES (1140, 'кантонное право', 'ru');
INSERT INTO `term` VALUES (1197, 'перевозчик', 'ru');
INSERT INTO `term` VALUES (1285, 'изменение в использовании земли', 'ru');
INSERT INTO `term` VALUES (1599, 'специальный представитель по опасным грузам', 'ru');
INSERT INTO `term` VALUES (1733, 'потребитель', 'ru');
INSERT INTO `term` VALUES (2019, 'снижение', 'ru');
INSERT INTO `term` VALUES (2049, 'делегация', 'ru');
INSERT INTO `term` VALUES (2120, 'разрушение', 'ru');
INSERT INTO `term` VALUES (2154, 'развитие', 'ru');
INSERT INTO `term` VALUES (2205, 'стандарт ДИН', 'ru');
INSERT INTO `term` VALUES (2281, 'врач', 'ru');
INSERT INTO `term` VALUES (2906, 'уполномоченный по вопросам охраны окружающей среды', 'ru');
INSERT INTO `term` VALUES (3004, 'Европейская программа восстановления ("план Маршалла")', 'ru');
INSERT INTO `term` VALUES (3145, 'автострада федерального значения', 'ru');
INSERT INTO `term` VALUES (3146, 'Федеральный закон по контролю за выбросами в атмосферу', 'ru');
INSERT INTO `term` VALUES (3150, 'питающее течение', 'ru');
INSERT INTO `term` VALUES (3642, 'географический атрибут', 'ru');
INSERT INTO `term` VALUES (3643, 'географическое распределение ресурсов', 'ru');
INSERT INTO `term` VALUES (3883, 'полномочия на проведение слушаний', 'ru');
INSERT INTO `term` VALUES (3927, 'Хельсинкская Конвенция', 'ru');
INSERT INTO `term` VALUES (4142, 'конференция ИМКО', 'ru');
INSERT INTO `term` VALUES (4168, 'импортер', 'ru');
INSERT INTO `term` VALUES (4949, 'Программа "Человек и биосфера"', 'ru');
INSERT INTO `term` VALUES (4978, 'отказ в работе', 'ru');
INSERT INTO `term` VALUES (5074, 'Марпольское соглашение', 'ru');
INSERT INTO `term` VALUES (5109, 'мэр', 'ru');
INSERT INTO `term` VALUES (5114, 'среда', 'ru');
INSERT INTO `term` VALUES (5118, 'мера', 'ru');
INSERT INTO `term` VALUES (5275, 'добыча твердых полезных ископаемых', 'ru');
INSERT INTO `term` VALUES (5324, 'мобильность (физич.)', 'ru');
INSERT INTO `term` VALUES (5533, 'природа', 'ru');
INSERT INTO `term` VALUES (5562, 'соседствующий владелец', 'ru');
INSERT INTO `term` VALUES (5779, 'обсерватория', 'ru');
INSERT INTO `term` VALUES (5947, 'Соглашение о запрете сброса отходов в Северное море (1974 г., г.Осло)', 'ru');
INSERT INTO `term` VALUES (5961, 'затопление', 'ru');
INSERT INTO `term` VALUES (5970, 'владелец отходов', 'ru');
INSERT INTO `term` VALUES (6042, 'Парижская Конвенция', 'ru');
INSERT INTO `term` VALUES (6089, 'пешеход', 'ru');
INSERT INTO `term` VALUES (6303, 'представитель завода', 'ru');
INSERT INTO `term` VALUES (6322, 'количественные характеристики завода (промышленность)', 'ru');
INSERT INTO `term` VALUES (6582, 'доисторические времена', 'ru');
INSERT INTO `term` VALUES (6598, 'предотвращение', 'ru');
INSERT INTO `term` VALUES (6648, 'процедура', 'ru');
INSERT INTO `term` VALUES (6653, 'технология MSR (ядерный реактор на расплавленных солях)', 'ru');
INSERT INTO `term` VALUES (6665, 'производство', 'ru');
INSERT INTO `term` VALUES (6707, 'программирование', 'ru');
INSERT INTO `term` VALUES (6748, 'охрана', 'ru');
INSERT INTO `term` VALUES (6995, 'восстановление', 'ru');
INSERT INTO `term` VALUES (7098, 'надежность', 'ru');
INSERT INTO `term` VALUES (7109, 'ремонт', 'ru');
INSERT INTO `term` VALUES (7158, 'остаток', 'ru');
INSERT INTO `term` VALUES (7432, 'санитарная помощь', 'ru');
INSERT INTO `term` VALUES (7463, 'сценарий', 'ru');
INSERT INTO `term` VALUES (7589, 'избирательность', 'ru');
INSERT INTO `term` VALUES (7704, 'Единый Европейский акт', 'ru');
INSERT INTO `term` VALUES (7971, 'использование космоса', 'ru');
INSERT INTO `term` VALUES (8066, 'изложение фактов', 'ru');
INSERT INTO `term` VALUES (8245, 'экономическая устойчивость', 'ru');
INSERT INTO `term` VALUES (8423, 'текстильная технология', 'ru');
INSERT INTO `term` VALUES (8457, 'толщина изолирующего слоя', 'ru');
INSERT INTO `term` VALUES (8890, 'цена', 'ru');
INSERT INTO `term` VALUES (9037, 'стирка белья', 'ru');
INSERT INTO `term` VALUES (9038, 'Вашингтонская конвенция по охране видов', 'ru');
INSERT INTO `term` VALUES (9104, 'источник отходов', 'ru');
INSERT INTO `term` VALUES (10091, 'воздействие шума в быту', 'ru');
INSERT INTO `term` VALUES (10252, 'Конференция в Рио-де-Жанейро', 'ru');
INSERT INTO `term` VALUES (10253, 'Стокгольмская Конференция', 'ru');
INSERT INTO `term` VALUES (10799, 'консультант по вопросам охраны окружающей среды и экологии', 'ru');
INSERT INTO `term` VALUES (10800, 'эколог-токсиколог', 'ru');
INSERT INTO `term` VALUES (11009, 'член парламента', 'ru');
INSERT INTO `term` VALUES (11059, 'баланс материалов', 'ru');
INSERT INTO `term` VALUES (11121, 'состояние окружающей среды', 'ru');
INSERT INTO `term` VALUES (11380, 'Женевская Конвенция', 'ru');
INSERT INTO `term` VALUES (11381, 'Ломейская Конвенция', 'ru');
INSERT INTO `term` VALUES (11382, 'Директива ЕС о правилах использования и хранения опасных химических веществ', 'ru');
INSERT INTO `term` VALUES (11416, 'Женевский Протокол', 'ru');
INSERT INTO `term` VALUES (11417, 'Монреальский Протокол', 'ru');
INSERT INTO `term` VALUES (11520, 'инспектор', 'ru');
INSERT INTO `term` VALUES (11529, 'право доступа к административным документам', 'ru');
INSERT INTO `term` VALUES (11584, 'государственный обвинитель', 'ru');
INSERT INTO `term` VALUES (11780, 'цикл (явление)', 'ru');
INSERT INTO `term` VALUES (13070, 'изменение', 'ru');
INSERT INTO `term` VALUES (13108, 'природная динамика', 'ru');
INSERT INTO `term` VALUES (13129, 'перспективный', 'ru');
INSERT INTO `term` VALUES (13131, 'гигиенист', 'ru');
INSERT INTO `term` VALUES (13578, 'миграция', 'ru');
INSERT INTO `term` VALUES (13756, 'долговечность', 'ru');
INSERT INTO `term` VALUES (13983, 'питающее течение', 'ru');
INSERT INTO `term` VALUES (14113, 'Рамсарская Конвенция', 'ru');
INSERT INTO `term` VALUES (14840, 'межправительственный', 'ru');
INSERT INTO `term` VALUES (14841, 'правительственный', 'ru');
INSERT INTO `term` VALUES (14846, 'научный', 'ru');
INSERT INTO `term` VALUES (14942, 'промышленный или коммерческий', 'ru');

-- Insert new definitions in English
INSERT INTO `scope` VALUES (70, "en", "", "");
INSERT INTO `scope` VALUES (174, "en", "", "Agenda 21, the Rio Declaration on Environment and Development, is a comprehensive programme of action to be achieved by governments, development agencies, United Nations organizations and independent sector groups in every area where human activity affects the environment. Agenda 21 was adopted by the United Nations Conference on Environment and Development, the Earth Summit. Agenda 21 is the response to the UN General Assembly's call, in December 1989, for a global meeting to devise strategies to halt and reverse the effects of environment degradation \"in the context of increased national and international efforts to promote sustainable and environmentally sound development in all countries\".(Source: WRIGHT)");
INSERT INTO `scope` VALUES (408, "en", "", "");
INSERT INTO `scope` VALUES (711, "en", "", "The condition of equilibrium among the components of a natural community such that their relative numbers remain fairly constant and their ecosystem is stable. Gradual readjustments to the composition of a balanced community take place continually in resp");
INSERT INTO `scope` VALUES (713, "en", "", "");
INSERT INTO `scope` VALUES (734, "en", "", "The Basel Convention on the Control of Transboundary movements on hazardous wastes and their disposal was an agreement drawn up under the auspices of the United Nations Environment Programme (UNEP). It came into effect in May 1992 and was adopted by 116 governments and the European Community. Its main aim was to impose strict controls on the trans-border transport of hazardous wastes, and on their disposal. It gives developing countries the right to turn away shipments of hazardous waste from their shores. It means that a country exporting substances that it considers hazardous has to get permission for their delivery from the proposed importer, who then has 60 days to issue a "prior informed consent". The ultimate goal of the convention is to cut the generation of hazardous wastes to a minimum.(Source: WRIGHT)");
INSERT INTO `scope` VALUES (780, "en", "", "Name given to the Convention on the Conservation of European Wildlife and Natural Habitats. It aims to protect all forms of endangered wildlife in specified parts of Europe. (Source: WRIGHT)");
INSERT INTO `scope` VALUES (958, "en", "", "Convention of the Conservation of Migratory Species of Wild Animals, which was drawn up to protect all migratory species considered to be endangered through all or part of their range. The Convention came into effect in 1983 and imposes strict conservatio");
INSERT INTO `scope` VALUES (983, "en", "", "");
INSERT INTO `scope` VALUES (1022, "en", "", "");
INSERT INTO `scope` VALUES (1140, "en", "", "");
INSERT INTO `scope` VALUES (1197, "en", "", "");
INSERT INTO `scope` VALUES (1285, "en", "", "");
INSERT INTO `scope` VALUES (1599, "en", "", "");
INSERT INTO `scope` VALUES (1733, "en", "", "A person who purchases goods and services for his own personal needs. (Source: CED)");
INSERT INTO `scope` VALUES (2019, "en", "", "");
INSERT INTO `scope` VALUES (2049, "en", "", "A person or group chosen to represent another or others. (Source: CED)");
INSERT INTO `scope` VALUES (2120, "en", "", "");
INSERT INTO `scope` VALUES (2154, "en", "", "Increasing the capacity to meet human needs and improve the quality of human life. (Source: JCU)");
INSERT INTO `scope` VALUES (2205, "en", "", "");
INSERT INTO `scope` VALUES (2281, "en", "", "A person licensed to practise medicine. (Source: CED)");
INSERT INTO `scope` VALUES (2906, "en", "", "");
INSERT INTO `scope` VALUES (3004, "en", "", "");
INSERT INTO `scope` VALUES (3145, "en", "", "A road or way that is open to public use as a matter of right whether or not a thoroughfare. (Source: WEBSTEa)");
INSERT INTO `scope` VALUES (3146, "en", "", "The 1974 act, which protects against environmentally harmful effects of air pollution, noise, vibration and similar occurrences, was redrafted on 14/5/90, and amended last on 23/11/95. It forms the basis of nation-wide, comprehensive law on air quality, n");
INSERT INTO `scope` VALUES (3150, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (3642, "en", "", "");
INSERT INTO `scope` VALUES (3643, "en", "", "The physical character and distribution of natural resources at the face of the Earth. The fundamental differences between land and ocean, latitudinal differences in insulation, spatial variations in receipts of precipitation, and patterns of geological composition and deformation of the Earth's crust together provide the basis for distinguishing definite geographical patterns of resource availability over the world.(Source: PARCORa)");
INSERT INTO `scope` VALUES (3883, "en", "", "");
INSERT INTO `scope` VALUES (3927, "en", "", "Adopted in April 1992, an agreement by Denmark, Estonia, Finland, Germany, Latvia, Lithuania, Poland, Russia, and Sweden on the protection of the marine environment of the Baltic Sea with an action plan to reduce pollution in areas around the Sea. (Sourc");
INSERT INTO `scope` VALUES (4142, "en", "", "Inter-Governmental Maritime Consultative Organisation has been changed into International Maritime Organisation in May 1982. A United Nations Specialized Agency, established in 1958 as the Inter-Governmental Maritime Consultative Organisation to provide a");
INSERT INTO `scope` VALUES (4168, "en", "", "Person or society receiving and buying goods and services from abroad. (Source: CED)");
INSERT INTO `scope` VALUES (4949, "en", "", "An UNESCO project started in the 1970s. It was launched to further long-term conservation of the Earth's ecosystems, based on sound scientific foundations. MAB results have increased scientific understanding of ecosystems and their inter-relationships. Th");
INSERT INTO `scope` VALUES (4978, "en", "", "Failure to function or defective functioning. (Source: CED)");
INSERT INTO `scope` VALUES (5074, "en", "", "International Convention for the Prevention of Pollution from Ships (1973). The first important IMO agreement on controlling pollution from ships, which deals not only with pollution by oil but also chemical, garbage and sewage. (Source: WRIGHT)");
INSERT INTO `scope` VALUES (5109, "en", "", "A governmental figure who is generally the principal administrative officer of a city or other municipal area. (Source: WESTS)");
INSERT INTO `scope` VALUES (5114, "en", "", "");
INSERT INTO `scope` VALUES (5118, "en", "", "The extent, quantity, amount, or degree of something as determined by measurement or calculation. (Source: CED)");
INSERT INTO `scope` VALUES (5275, "en", "", "");
INSERT INTO `scope` VALUES (5324, "en", "", "");
INSERT INTO `scope` VALUES (5533, "en", "", "All natural phenomena and plant and animal life, as distinct from man and his creations. (Source: CED)");
INSERT INTO `scope` VALUES (5562, "en", "", "Person who lives in close proximity to another or owns a contiguous property. (Source: WESTSa)");
INSERT INTO `scope` VALUES (5779, "en", "", "Any building or structure providing an extensive view of its surroundings. (Source: CED)");
INSERT INTO `scope` VALUES (5947, "en", "", "The Oslo Treaty came into force in 1974 and banned the dumping of certain wastes, such as mercury, cadmium and persistent plastics, in the North Sea. The Oslo Treaty has similar black lists and grey lists to the London Convention of substances that are banned from dumping. The treaty was signed by the governments of Belgium, Denmark, France, the former West Germany, the Netherlands, Norway, Sweden and the UK. Three North Sea Conferences were subsequently organized. At the first, in 1984, it was agreed that the phasing out of the use and discharge of polychlorinated biphenyls (PCBs) should be stepped up, that wastes including sewage sludge, should not be dumped in the North Sea and that specified hazardous waste should come under more stringent control. In 1987, at the second conference, it was agreed to reduce by half discharge of \"substances that are toxic, persistent and liable to bioaccumulate\" by 1995. Restrictions on the use of marine incineration and the dumping of sewage sludge were also agreed. At the third conference, in 1990, the eight signatories to the original treaty and Switzerland had agreed to stop dumping sewage sludge at sea, but the UK said it would only phase this out by 1998. (Source: WRIGHT)");
INSERT INTO `scope` VALUES (5961, "en", "", "");
INSERT INTO `scope` VALUES (5970, "en", "", "");
INSERT INTO `scope` VALUES (6042, "en", "", "Convention for the Prevention of Marine Pollution from land-based sources. An International agreement signed in March 1974 by Denmark, France, Iceland, Luxembourg, The Netherlands, Norway, Spain, Sweden, the UK and West Germany to augment earlier agreements controlling the dumping of wastes at sea. (Source: ALL)");
INSERT INTO `scope` VALUES (6089, "en", "", "One walking as distinguished from one travelling by car or cycle. (Source: WEBSTE)");
INSERT INTO `scope` VALUES (6303, "en", "", "");
INSERT INTO `scope` VALUES (6322, "en", "", "");
INSERT INTO `scope` VALUES (6582, "en", "", "Human history in the period before recorded events, known mainly through archaeological discoveries.");
INSERT INTO `scope` VALUES (6598, "en", "", "The act of keeping from happening, especially by taking precautionary action. (Source: CED)");
INSERT INTO `scope` VALUES (6648, "en", "", "");
INSERT INTO `scope` VALUES (6653, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (6665, "en", "", "");
INSERT INTO `scope` VALUES (6707, "en", "", "Preparing a detailed sequence of operating instructions for a particular problem to be run on a digital computer. (Source: MGH)");
INSERT INTO `scope` VALUES (6748, "en", "", "The act of defending from trouble, harm, attack, etc. (Source: CED)");
INSERT INTO `scope` VALUES (6995, "en", "", "The act or process of restoring something to an original or formal condition, of claiming back a possession, etc. (Source: CED)");
INSERT INTO `scope` VALUES (7098, "en", "", "");
INSERT INTO `scope` VALUES (7109, "en", "", "");
INSERT INTO `scope` VALUES (7158, "en", "", "Any materials, solid or semisolid, left over from incineration, evaporation or other processes. (Source: DEE /  ISEP)");
INSERT INTO `scope` VALUES (7432, "en", "", "");
INSERT INTO `scope` VALUES (7463, "en", "", "Conditions of the environment chosen for a given survey or activity. (Source: RRDA)");
INSERT INTO `scope` VALUES (7589, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (7704, "en", "", "A 1987 amendment to the founding treaties dealing primarily with the internal market, European Political Cooperation (EPC), and institutional reform of the EC. The measures covered by the legislation include: the elimination of frontiers controls, the acceptance throughout the market of professional qualification, the acceptance of natural standards for product harmonization, open tendering for public supply contracts, the free movement of capital between states, etc. (Source: INFOAB / DICLAW)");
INSERT INTO `scope` VALUES (7971, "en", "", "");
INSERT INTO `scope` VALUES (8066, "en", "", "A report or announcement of something that has been objectively verified. (Source: ISEP)");
INSERT INTO `scope` VALUES (8245, "en", "", "Adoption of energy and environmental policies which would not threaten the world environment, yet at the same time allow economic growth. (Source: BRACK)");
INSERT INTO `scope` VALUES (8423, "en", "", "Technology employed in the transformation of various kinds of fibres or yarns into woven fabrics or clothes. (Source: CEDa)");
INSERT INTO `scope` VALUES (8457, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (8890, "en", "", "Worth, merit or importance of something. (Source: CED)");
INSERT INTO `scope` VALUES (9037, "en", "", "");
INSERT INTO `scope` VALUES (9038, "en", "", "A Convention adopted in 1973, providing for the regulation of trade in whole plants and animals, dead or alive, and their readily recognizable parts and derivatives. Excessive international trade has contributed directly to the decline of many wild population of rare and endangered species. The Convention states that a protected species may not be the subject of international trade without a permit granted under the CITES procedures.(Source: GILP96)");
INSERT INTO `scope` VALUES (9104, "en", "", "Sources of waste generation, typically used to refer to the domestic, commercial/industrial, or construction and demolition sectors. (Source: USERS)");
INSERT INTO `scope` VALUES (10091, "en", "", "");
INSERT INTO `scope` VALUES (10252, "en", "", "Earth Summit held in Rio de Janeiro in June 1992, during which the Rio Declaration, a 27-page document, was approved, laying down broad principles of environmentally-sound development. The principal outcomes of the Summit were a declaration, conventions on controlling climate change and preserving biological diversity, and a lengthy agenda outlining the extent of global environmental problems and the measures needed to tackle them in order to achieve the agreed goal of "sustainable development". Opinion was divided as to how far the conference could be termed a success. Many environmentalists stressed its failure to set binding targets for resolving environmental problems, and to address adequately the links between third world poverty and environmental degradation. Others, such as many of the world leaders who attended the conference stressed that it should be seen as a first step towards sustainable development, and an important acknowledgment of the seriousness of the problem and of the fact that global co-operation is needed to overcome it.(Source: PHC)");
INSERT INTO `scope` VALUES (10253, "en", "", "The UN Conference on the Human Environment, held in Stockholm in 1972 attended by representatives of nations. Declarations were made aimed at protection of the environment, and the concept of the UN body the United Nations Environment Programme, UNEP, was agreed. An anniversary conference was held in Stockholm in 1982 on \"acidity in the environment\". (Source: BRACK)");
INSERT INTO `scope` VALUES (10799, "en", "", "");
INSERT INTO `scope` VALUES (10800, "en", "", "An environmental health professional who determines the adverse health effects, and the mechanisms of those effects, resulting from exposure to physical, chemical, and biological aspects in the human environment. (Source: KOREN)");
INSERT INTO `scope` VALUES (11009, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (11059, "en", "", "");
INSERT INTO `scope` VALUES (11121, "en", "", "Condition and trends of different environmental compartments and systems, as regards the influence of human populations, the consumption of non-renewable resources and sustainable development. (Source: RRDA)");
INSERT INTO `scope` VALUES (11380, "en", "", "A Convention initiated by the UN ECE for the purpose of curbing the incidence of acid rain arising from the long range transportation of pollutants, most notably sulphur dioxide. The Convention was signed in 1979 and came into effect in 1983. Basically, it was a statement of desirable objectives without numerical limits. In 1983 the Nordic Countries proposed a 30% reduction in sulphur dioxide emissions in all member countries to be achieved by 1993. The move was welcomed by most member countries. Regulations began to be introduced requiring power plants to be equipped with high-performance gas scrubbers, unless being retired by 1993.(Source: GILP96)");
INSERT INTO `scope` VALUES (11381, "en", "", "The Lomé Conventions are multilateral trade and development agreements between the EU and the 70 ACP countries. They give the ACP countries associated status with the EU, offering them not only financial assistance but also substantial trading advantages on exports to the EU. The Conventions are the heart of the EU's development policy. Lomé I was concluded in 1975, running for five years; it was followed by Lomé II (1980), Lomé III (1985) and finally Lomé IV in 1990, which will run for 10 years, with a budget of ECU 13.2 billion over the first five years. The main focus of the Convention is the long-term development of the countries involved. Lomé IV also incorporates agreements for the protection of human rights and the development of democracy.(Source: INFREG)");
INSERT INTO `scope` VALUES (11382, "en", "", "Directive issued by the European Community in 1981 that obliged industries to notify the authorities, their own workers, and local residents of dangerous chemicals held, while also laying down rules for the storage of specified chemicals. (Source: GILP96)");
INSERT INTO `scope` VALUES (11416, "en", "", "Protocol of Geneva Convention concerning the control of emissions of nitrogen oxides and the reduction of sulphur emissions or their transboundary fluxes by at least 30%. (Source: UNTERM)");
INSERT INTO `scope` VALUES (11417, "en", "", "An international agreement reached in 1988 by over 30 countries, aimed at protecting the ozone layer by controlling the emissions of chlorofluorocarbons (CFCs) and halons. Under the agreement, initiated by UNEP, CFC consumption is to be progressively reduced worldwide, being phased out completely by 1996. The consumption of halons was not to be allowed to increase above the levels of 1988. The protocol followed the Convention for the protection of the ozone layer (the Vienna convention) adopted in 1985. By the mid-1990s, the Third World continued to provide a substantial market for ozone-damaging chemicals made, but not sold, elsewhere.(Source: GILP96)");
INSERT INTO `scope` VALUES (11520, "en", "", "");
INSERT INTO `scope` VALUES (11529, "en", "", "");
INSERT INTO `scope` VALUES (11584, "en", "", "An officer of government whose function is the prosecution of criminal actions, or suits partaking of the nature of criminal actions. (Source: WESTS)");
INSERT INTO `scope` VALUES (11780, "en", "", "A completed series of events that follows or is followed by another series of similar events occurring in the same sequence. (Source: CED)");
INSERT INTO `scope` VALUES (13070, "en", "", "The act of altering or the state of being altered. (Source: CED)");
INSERT INTO `scope` VALUES (13108, "en", "", "");
INSERT INTO `scope` VALUES (13129, "en", "", "");
INSERT INTO `scope` VALUES (13131, "en", "", "A person skilled in the practice of hygiene. (Source: CED)");
INSERT INTO `scope` VALUES (13578, "en", "", "The act of going from one region, country or place to another. (Source: CED)");
INSERT INTO `scope` VALUES (13756, "en", "", "");
INSERT INTO `scope` VALUES (13983, "en", "", "");
INSERT INTO `scope` VALUES (14113, "en", "", "The Convention's broad aims are to halt the worldwide loss of wetlands and to conserve, through wise use and management, those that remain. There are currently over 80 countries which are Contracting Parties to the Ramsar Convention covering 75% of the wo");
INSERT INTO `scope` VALUES (14840, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (14841, "en", "", "No definition needed. (Source: NDN)");
INSERT INTO `scope` VALUES (14846, "en", "", "");
INSERT INTO `scope` VALUES (14942, "en", "", "No definition needed. (Source: NDN)");

-- Insert new definitions in Russian
INSERT INTO `scope` VALUES (70, 'ru', '', 'Выполненное действие или акт; судебные действия, произведенные одной стороной против другой.');
INSERT INTO `scope` VALUES (174, 'ru', '', '"Повестка дня на XXI век", или Декларация Рио по окружающей среде и развитию, представляет собой программу действий, которую предстоит выполнить правительствам, агентствам по развитию, организациям системы ООН и независимым организациям в каждой области, в которой деятельность человека воздействует на окружающую среду. "Повестка дня на XXI век" была принята на Конференции ООН по окружающей среде и развитию, созванной по инициативе Генеральной Ассамблеи ООН. Этот международный форум был созван для того, чтобы разработать стратегии, ограничивающие и поворачивающие вспять отрицательные последствия деградации окружающей среды "в контексте возросших национальных и международных усилий по содействию устойчивому и экологически здоровому развитию".');
INSERT INTO `scope` VALUES (711, 'ru', '', 'Состояние равновесия между компонентами природного сообщества, которое обеспечивает приблизительно постоянную величину их относительной численности и стабильность их экосистемы. Процесс приспособления компонентов сбалансированного сообщества к изменяющимся природным, климатическим и пр. условиям происходит постоянно. Удаляя или добавляя конкретные виды растений или животных в экосистемы, загрязняя окружающую среду, уничтожая естественную среду обитания животных, увеличивая собственную численность, люди могут внести серьезные изменения в природный баланс, часть которых может быть необратима.');
INSERT INTO `scope` VALUES (713, 'ru', '', 'Процесс определения разницы между суммой всех поступлений и суммой всех расходов по любой статье либо погашение задолженности по конкретному счету.');
INSERT INTO `scope` VALUES (734, 'ru', '', 'Базельская Конвенция по контролю за трансграничным переносом ядовитых отходов и их утилизацией была разработана под эгидой Программы Организации Объединенных Наций по окружающей среде. Вступила в силу в мае 1992 г. и подписана правительствами 116 государств и Евросоюзом. Цель Конвенции - установить строгий контроль за трансграничной перевозкой ядовитых отходов и их утилизацией. Предоставляет право развивающимся странам не подпускать суда с ядовитыми отходами близко к своим берегам. По условиям Конвенции, страна, экспортирующая отходы, представляющиеся ядовитыми, должна получить разрешение у предполагаемого импортера, который в течение 60 дней должен выдать документ, т. н. "согласие с предварительным уведомлением". Конечная цель Конвенции - свести к минимуму производство ядовитых отходов.');
INSERT INTO `scope` VALUES (780, 'ru', '', 'Термин, применяемый по отношению к Конвенции по сохранению дикой природы и естественной среды обитания в Европе. Цель Конвенции - защитить в Европе все формы дикой природы, чье существование находится под угрозой уничтожения.');
INSERT INTO `scope` VALUES (958, 'ru', '', 'Конвенция о сохранении мигрирующих видов диких животных была подписана в целях защиты всех мигрирующих видов, чье существование полностью или частично находится под угрозой уничтожения. Конвенция вступила в силу в 1983 году и предполагает строгую ответственность за сохранение видов животных. Охота и отлов 51 вида животных, находящихся под угрозой исчезновения, большинство из которых - птицы, строго запрещены. Конвенция также призывает страны, граничащие вдоль маршрутов миграции животных,  заключать соглашения между собой в целях защиты еще 2 тыс. видов.');
INSERT INTO `scope` VALUES (1599, 'ru', '', 'Уполномоченный представитель правительства, регулирующий производство, использование, транспортировку и обезвреживание материалов, представляющих угрозу человеческому здоровью и окружающей среде, особенно это касается материалов, которые являются токсичными, коррозионными, воспламеняющимися, взрывоопасными или химически активными.');
INSERT INTO `scope` VALUES (1733, 'ru', '', 'Лицо, приобретающее товары и услуги для личного потребления.');
INSERT INTO `scope` VALUES (2049, 'ru', '', 'Одно или несколько лиц, избранных представлять интересы другого лица или группы лиц.');
INSERT INTO `scope` VALUES (2154, 'ru', '', 'Увеличение возможностей удовлетворять людские потребности и улучшать качество жизни людей.');
INSERT INTO `scope` VALUES (2281, 'ru', '', 'Лицо, обладающее лицензией на оказание медицинской помощи и услуг.');
INSERT INTO `scope` VALUES (3145, 'ru', '', 'Дорога или путь, открытые для общественного использования в соответствии с законом, независимо от того, являются они магистральными или нет.');
INSERT INTO `scope` VALUES (3146, 'ru', '', 'Закон 1974 г., призванный защитить от экологически вредных последствий загрязнения воздуха, шумового загрязнения, вибрации и схожих видов загрязнения, был переформулирован 14.05.90. и изменен 23.11.95. Создает основу для общенационального, всеобъемлющего закона по качеству воздуха, снижению шума и безопасности на предприятиях. Среди прочего, закон содержит правила для строительства и содержания экологически опасных объектов, требования к веществам, составу и работе автомобильных двигателей, защите конкретных районов, назначению представителей компаний для контроля за выбросами и соблюдением экологических требований.');
INSERT INTO `scope` VALUES (3150, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (3642, 'ru', '', 'Показатель или данные, имеющие отношение к географическому признаку, например, географическое расположение участка суши, его структура, свойства и пр.');
INSERT INTO `scope` VALUES (3643, 'ru', '', 'Физический тип и распределение природных ресурсов на планете. Базовые различия между сушей и океаном, обособленность в зависимости от широты, различия в уровне осадков на различных участках земной поверхности, геологический состав и деформация земной коры обеспечивают возможность  составить детальные карты распределения природных ресурсов по всему миру.');
INSERT INTO `scope` VALUES (3927, 'ru', '', 'Соглашение, принятое в апреле 1992 года Данией, Эстонией, Финляндией, Германией, Латвией, Литвой, Польшей, Россией и Швецией, направленное на защиту морской среды Балтийского моря, сопровождаемое планом действий по сокращению уровней загрязнения в регионах, окружающих Балтийское море.');
INSERT INTO `scope` VALUES (4142, 'ru', '', 'Межправительственная морская консультативная организация в мае 1982 года была переименована в Международную морскую организацию (IMO). Эта структура, созданная как специализированная организация системы ООН, содействует сотрудничеству и обмену информацией, связанной с международными фрахтовыми операциями, в частности, в отношении безопасности и загрязнения морской среды.');
INSERT INTO `scope` VALUES (4168, 'ru', '', 'Лицо или организация, получающая или покупающая товары и услуги за границей.');
INSERT INTO `scope` VALUES (4949, 'ru', '', 'Проект ЮНЕСКО, начатый в 1970 году. Цель проекта - долгосрочное сохранение экосистем Земли, основанное на научных подходах. Реализация программы "Человек и биосфера" привела к возросшему научному пониманию экосистем и их взаимоотношений. Исследования открыли новые научные темы, в частности, в области изучения тропических лесов. Были открыты новые виды, а также новые терапевтические свойства растений. К началу 80-х годов ХХ века около 25% западных медицинских препаратов содержало по меньшей мере один компонент, произведенный тропическим лесом.');
INSERT INTO `scope` VALUES (4978, 'ru', '', 'Сбой или дефект в функциях.');
INSERT INTO `scope` VALUES (5074, 'ru', '', 'Международная Конвенция  о предотвращении загрязнения моря судами (1973). Первое важное соглашение Международной морской организации в области контроля за загрязнением моря судами, которое регулирует не только загрязнение нефтью, но также загрязнение химическими, канализационными и бытовыми отходами.');
INSERT INTO `scope` VALUES (5109, 'ru', '', 'Государственный чиновник, который, как правило возглавляет главный административный орган в городе или другом муниципальном образовании.');
INSERT INTO `scope` VALUES (5114, 'ru', '', 'Вещество или материал, который выступает в качестве проводника или переносчика для какого-либо соединения или химиката, например, продукты питания, почва, вода, воздух; также физическая форма или носитель данных, например, бумага, пленка, диск, магнитная лента и др. материалы, на которые может быть записана информация.');
INSERT INTO `scope` VALUES (5118, 'ru', '', 'Степень, количество, величина, уровень чего-либо, что определяется в результате измерения или расчета.');
INSERT INTO `scope` VALUES (5324, 'ru', '', 'Способность отдельных лиц и групп менять род занятий или профессию, а также физически перемещаться из одного места в другое.');
INSERT INTO `scope` VALUES (5533, 'ru', '', 'Все явления природы, растения и животные, в отличие от человека и результатов его деятельности.');
INSERT INTO `scope` VALUES (5562, 'ru', '', 'Лицо, проживающее близко к другому, или владеющее расположенной рядом собственностью.');
INSERT INTO `scope` VALUES (5779, 'ru', '', 'Строение или конструкция, обеспечивающая широкий обзор окрестностей.');
INSERT INTO `scope` VALUES (5947, 'ru', '', 'Соглашение вступило в силу в 1974 г. и запретило сброс в Северное море определенных видов отходов, например, ртуть и кадмийсодержащие отходы, а также стойкие пластмассы. Все запрещенные соглашением вещества образуют "черный" и "серый" списки, которые приложены к основному тексту. Соглашение подписали правительства Бельгии, Дании, Франции, Германии, Нидерландов, Норвегии, Швеции и Великобритании. После принятия соглашения прошли три конференции по Северному морю. На первой конференции в 1984 г. было решено, что необходимо усилить работу по постепенному запрету выбросов полихлорированных бифенилов, что отходы, включая канализационный отстой, нельзя сбрасывать в Северное море, а также усилить контроль за утилизацией конкретных опасных отходов. На второй конференции в 1987 г. было принято решение уменьшить вдвое к 1995 г. выброс веществ, которые являются токсичными, стойкими или могут биологически накапливаться. Были согласованы ограничения на сброс канализационных стоков, а также на сжигание отходов в море. На третьей конференции в 1990 г. восемь государств, подписавших соглашение, а также Швейцария решили прекратить сброс канализационных стоков в море, однако Великобритания заявила, что сможет этого достичь только к 1998 г.');
INSERT INTO `scope` VALUES (5970, 'ru', '', 'Владелец отходов, полученных в местах проживания людей или обитания животных, либо материалов, полученных в ходе промышленных процессов.');
INSERT INTO `scope` VALUES (6042, 'ru', '', 'Конвенция о предотвращении загрязнении моря от хозяйственной деятельности на суше. Международное соглашение, подписанное в 1974 г. Данией, Францией, Исландией, Люксембургом, Нидерландами, Норвегией, Испанией, Швецией, Великобританией и Германией, расширившее более ранние договоренности по контролю за выбросами отходов в море.');
INSERT INTO `scope` VALUES (6089, 'ru', '', 'Лицо, идущее пешком, в отличие от лица, путешествующего за рулем автомобиля или на велосипеде.');
INSERT INTO `scope` VALUES (6303, 'ru', '', 'Лицо, уполномоченное действовать от имени рабочих или управления компании, например, на профессиональной конвенции или собрании по вопросам труда.');
INSERT INTO `scope` VALUES (6582, 'ru', '', 'Человеческая история до начала записи исторической хронологии, о ней обычно можно узнать, изучая археологические раскопки.');
INSERT INTO `scope` VALUES (6598, 'ru', '', 'Действие, связанное с предупреждением наступления чего-либо, особенно в результате принятия предупредительных, профилактических мер.');
INSERT INTO `scope` VALUES (6648, 'ru', '', 'Предписанное действие или манера проведения какого-либо процесса.');
INSERT INTO `scope` VALUES (6653, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (6665, 'ru', '', 'Использование ресурсов для изготовления товаров или оказания услуг, имеющих меновую стоимость.');
INSERT INTO `scope` VALUES (6707, 'ru', '', 'Подготовка детальной поэтапной инструкции для решения конкретной задачи на компьютере.');
INSERT INTO `scope` VALUES (6748, 'ru', '', 'Действие, связанное с защитой от неприятностей, ущерба, нападения и пр.');
INSERT INTO `scope` VALUES (6995, 'ru', '', 'Действие или процесс восстановления чего-либо в первоначальном виде или форме, требование обратно своей собственности и пр.');
INSERT INTO `scope` VALUES (7098, 'ru', '', 'Вероятность того, что инструмент, прибор или процесс будут работать хорошо при определенных условиях в течение определенного периода времени.');
INSERT INTO `scope` VALUES (7109, 'ru', '', 'Процесс приведения чего-либо в улучшенное состояние в результате ремонтных или отделочных работ.');
INSERT INTO `scope` VALUES (7158, 'ru', '', 'Любые материалы в твердом или размягченном виде, оставшиеся после процессов сжигания, выпаривания и др.');
INSERT INTO `scope` VALUES (7463, 'ru', '', 'Условия окружающей среды, выбранные для данного исследования или вида деятельности.');
INSERT INTO `scope` VALUES (7589, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (7704, 'ru', '', 'Дополнение 1987 года к основополагающим договорам, касающееся образования внутреннего рынка, Европейского политического сотрудничества (ЕПС) и институциональной реформы Евросоюза. Меры, предусмотренные этим документом, включают: устранение контроля на границе для физических лиц, взаимное признание свидетельств о высшем и профессиональном образовании в странах-членах, проведение открытых торгов для осуществления государственных закупок, свободное передвижение капиталов между государствами и пр.');
INSERT INTO `scope` VALUES (8066, 'ru', '', 'Отчет или объявление чего-либо, получившего официальное подтверждение.');
INSERT INTO `scope` VALUES (8245, 'ru', '', 'Реализация энергетической и экологической политики, которые не будут угрожать окружающей среде во всем мире и одновременно будут способствовать экономическому росту.');
INSERT INTO `scope` VALUES (8423, 'ru', '', 'Технология, используемая в процессе преобразования различных волокон или нитей в ткани или одежду.');
INSERT INTO `scope` VALUES (8457, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (8890, 'ru', '', 'Ценность, стоимость, важность чего-либо.');
INSERT INTO `scope` VALUES (9037, 'ru', '', 'Процесс чистки или удаления грязи и других загрязняющих веществ обычно при помощи воды либо другой жидкости.');
INSERT INTO `scope` VALUES (9038, 'ru', '', 'Конвенция, принятая в 1973 г., предусматривает регулирование торговли целыми растениями и животными, живыми или мертвыми, а также частями их тел и материалами, изготовленными на их основе. Расширенная международная торговля имеет прямую связь с сокращением многих популяций редких видов и видов, существование которых находится под угрозой. В Конвенции указывается, что охраняемые виды не могут являться объектом торговли без разрешения, выданного в соответствии с процедурой CITES.');
INSERT INTO `scope` VALUES (9104, 'ru', '', 'Источники образования отходов обычно находятся в таких хозяйственных секторах, как  промышленная/коммерческая деятельность, строительство и разрушение домов, бытовая деятельность.');
INSERT INTO `scope` VALUES (10252, 'ru', '', 'Конференция на высшем уровне по окружающей среде и развитию состоялась в июне 1992 г. в Рио-де-Жанейро, на которой была принята "Декларация Рио", 27-страничный документ, положивший основу принципам экологически устойчивого развития. Основными итоговыми документами этой конференции были: декларация, конвенции по контролю за изменением климата и сохранению биоразнообразия, а также пространная повестка дня, содержащая описания масштабов глобальных экологических проблем и мер, которые необходимо принять для достижения "устойчивого развития". Мнения разделились по поводу того, насколько работу конференции можно назвать успешной. Многие экологи посчитали ее провальной, потому что ей не удалось установить обязательных целей для решения экологических проблем, а также серьезно обсудить связь между бедностью стран "третьего мира " и экологическими проблемами. Другие, как, например, лидеры многих государств, подчеркивали важность этой конференции в качестве первого шага к достижению устойчивого развития, а также для серьезной оценки глобальных экологических проблем и признания необходимости международного сотрудничества для их решения.');
INSERT INTO `scope` VALUES (10253, 'ru', '', 'Конференция ООН по окружающей среде состоялась в Стокгольме в 1972 г. На конференции были приняты декларации по защите окружающей среды, а также была согласована основополагающая концепция по созданию специализированной организации ООН - Программы ООН по окружающей среде (ЮНЕП). Десять лет спустя, в 1982 г.,  в Стокгольме состоялась юбилейная конференция.');
INSERT INTO `scope` VALUES (10800, 'ru', '', 'Профессионал в области санитарного состояния окружающей среды, определяющий отрицательное воздействие на здоровье и его механизм со стороны физических, химических и биологических аспектов окружающей человека среды.');
INSERT INTO `scope` VALUES (11009, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (11121, 'ru', '', 'Условия и тенденции различных экологических сообществ и систем по отношению к воздействию человека.');
INSERT INTO `scope` VALUES (11380, 'ru', '', 'Конвенция, инициатором которой выступила Европейская экономическая комиссия ООН - ЕЭК ООН. Цель Конвенции - борьба с выпадением кислотных осадков, являющихся результатом переноса на дальние расстояния загрязняющих веществ, главным образом, оксидов серы. Конвенция была подписана в 1979 г. и вступила в силу в 1983 г. В принципе, Конвенция содержит в себе общее изложение желаемых целей без определения конкретных цифровых показателей. В 1983 г. северные страны предложили добиться 30%-ного снижения выбросов оксидов серы в своем регионе к 1993 г. Начался процесс принятия законов, обязывающих устанавливать высокоэффективные газовые скрубберы на всех электростанциях, исключая те станция, которые должны были быть закрыты к 1993 г.');
INSERT INTO `scope` VALUES (11381, 'ru', '', 'Ломейские Конвенции представляют собой многосторонние соглашения по торговле и развитию между странами-членами ЕС и 70 развивающимися государствами Африки, Карибского бассейна и Тихоокеанского региона. По условиям этих конвенций развивающимся государствам предоставляется ассоциированный статус при ЕС, финансовая помощь, а также значительные торговые преимущества при экспорте своих товаров в ЕС. Ломейские Конвенции составляют основу политики ЕС в отношении развивающихся стран. Первая Ломейская Конвенция была заключена в  1975 г. сроком на пять лет. За ней последовала вторая Ломейская Конвенция в 1980 г., третья - в 1985 г. и четвертая - в 1990 г., действие которой должно было закончиться в 2000 г.; в первые пять лет из бюджета ЕС в рамках четвертой Конвенции было выделено 13,2 млрд. экю. Основное внимание в Ломейских Конвенциях уделяется долгосрочному развитию участвующих стран. Четвертая Конвенция также включает соглашения о защите гражданских прав и развитии демократии.');
INSERT INTO `scope` VALUES (11382, 'ru', '', 'Директива, изданная в ЕС в 1981 г., обязывающая промышленные предприятия уведомлять государственные органы, собственных работников и местных жителей о наличии на своих производствах опасных химикатов, а также устанавливающая правила хранения указанных химикатов.');
INSERT INTO `scope` VALUES (11416, 'ru', '', 'Протокол к Женевской Конвенции, касающийся контроля за уровнем выброса оксидов азота и снижения выбросов оксидов серы либо их трансграничного переноса на 30%.');
INSERT INTO `scope` VALUES (11417, 'ru', '', 'Международное соглашение, подписанное более чем 30 государствами в 1988 г., направленное на защиту озонового слоя в результате сокращения выбросов хлорфторуглеродов (газов CFC) и галонов. В соответствии с условиями этого соглашения, инициатором которого выступила ЮНЕП, использование газов CFC во всем мире должно постепенно сокращаться и прекратиться полностью к 1996 г. Использование галонов должно оставаться на уровне 1988 г. Протокол был принят вслед за принятием в 1985 г. Конвенции по охране озонового слоя (Венской Конвенции). К середине 90-х годов страны третьего мира продолжали оставаться крупными потребителями озоноразрушающих веществ, изготавливаемых, но непродаваемых в других регионах мира.');
INSERT INTO `scope` VALUES (11520, 'ru', '', 'Государственный чиновник, уполномоченный или назначенный проверять какую-либо регулируемую деятельность для установления ее соответствия федеральным, государственным или муниципальным законам.');
INSERT INTO `scope` VALUES (11584, 'ru', '', 'Государственный чиновник, поддерживающий обвинение по уголовным преступлениям или в рамках дел, заведенных на действия, преследуемых уголовным правом.');
INSERT INTO `scope` VALUES (11780, 'ru', '', 'Завершенная серия событий, за которой следуют аналогичные события или которая следует за аналогичными событиями, происходящими в одной и той же последовательности.');
INSERT INTO `scope` VALUES (13070, 'ru', '', 'Действие по изменению или состояние изменения.');
INSERT INTO `scope` VALUES (13129, 'ru', '', 'Термин характеризует действия или процесс подготовки к какому-либо прогнозируемому будущему состоянию или событию.');
INSERT INTO `scope` VALUES (13131, 'ru', '', 'Человек, получивший профессиональную подготовку в области гигиены.');
INSERT INTO `scope` VALUES (13578, 'ru', '', 'Перемещение в другой регион, страну или с одного места в другое.');
INSERT INTO `scope` VALUES (13756, 'ru', '', 'Состояние или способность длиться или пребывать в определенном состоянии, не подвергаясь износу, разложению или значительному разрушению.');
INSERT INTO `scope` VALUES (14113, 'ru', '', 'Главная цель Конвенции - прекратить разрушение переувлажненных земель и сохранить оставшиеся в результате широкого использования и управления. В настоящее время свыше 80 стран являются участниками Рамсарской Конвенции, что составляет 75% территории всего мира. Секретариат Рамсарской Конвенции находится в г. Гланд (Швейцария) и осуществляет техническую поддержку выполнения условий Конвенции. Секретариат существует на средства, ежегодно предоставляемые странами-участницами Конвенции. Каждые три года проходит конференция стран-участниц, на которой рассматривается деятельность по реализации Конвенции, принимаются новые планы и инициативы.');
INSERT INTO `scope` VALUES (14840, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (14841, 'ru', '', 'Не требует толкования.');
INSERT INTO `scope` VALUES (14942, 'ru', '', 'Не требует толкования.');
