UPDATE `concept_group` SET description="IGAZGATÁS, IRÁNYÍTÁS, POLITIKAI VONAL, POLITIKATUDOMÁNY, INTÉZMÉNYEK, TERVEZÉS" WHERE id_group=96 and langcode='hu';
UPDATE `concept_group` SET description="MEZŐGAZDASÁG, ERDÉSZET, ÁLLATTENYÉSZTÉS, HALÁSZAT" WHERE id_group=234 and langcode='hu';
UPDATE `concept_group` SET description="LÉGKÖR (levegő, éghajlat)" WHERE id_group=618 and langcode='hu';
UPDATE `concept_group` SET description="BIOSZFÉRA (szervezetek, ökoszisztémák)" WHERE id_group=893 and langcode='hu';
UPDATE `concept_group` SET description="ANTROPOSZFÉRA (épített környezet, emberi települések, földrendezés)" WHERE id_group=1062 and langcode='hu';
UPDATE `concept_group` SET description="KÉMIA/VEGYÉSZET, ANYAGOK, FOLYAMATOK" WHERE id_group=1349 and langcode='hu';
UPDATE `concept_group` SET description="INFORMÁCIÓ, OKTATÁS, KULTÚRA, KÖRNYEZETI TUDATOSSÁG" WHERE id_group=1922 and langcode='hu';
UPDATE `concept_group` SET description="KÖZGAZDASÁGTAN, PÉNZÜGY" WHERE id_group=2504 and langcode='hu';
UPDATE `concept_group` SET description="ENERGIA" WHERE id_group=2711 and langcode='hu';
UPDATE `concept_group` SET description="TÁRSADALMI VONATKOZÁSOK, KÖRNYEZETPOLITIKAI INTÉZKEDÉSEK" WHERE id_group=2894 and langcode='hu';
UPDATE `concept_group` SET description="EGÉSZSÉG, TÁPLÁLKOZÁS" WHERE id_group=3875 and langcode='hu';
UPDATE `concept_group` SET description="EMBERI TEVÉKENYSÉGEK ÉS TERMÉKEK, KÖRNYEZETRE GYAKOROLT HATÁS" WHERE id_group=4044 and langcode='hu';
UPDATE `concept_group` SET description="HIDROSZFÉRA (édesvíz, tengervíz, vizek)" WHERE id_group=4125 and langcode='hu';
UPDATE `concept_group` SET description="IPAR, MESTERSÉGEK, TECHNOLÓGIA, BERENDEZÉSEK" WHERE id_group=4281 and langcode='hu';
UPDATE `concept_group` SET description="FÖLD (táj, földrajz)" WHERE id_group=4630 and langcode='hu';
UPDATE `concept_group` SET description="TÖRVÉNYHOZÁS, NORMÁK, EGYEZMÉNYEK" WHERE id_group=4750 and langcode='hu';
UPDATE `concept_group` SET description="LITOSZFÉRA (talaj, földtani folyamatok)" WHERE id_group=4856 and langcode='hu';
UPDATE `concept_group` SET description="KIEGÉSZÍTŐ LISTÁK" WHERE id_group=5306 and langcode='hu';
UPDATE `concept_group` SET description="TERMÉSZETI KÖRNYEZET, EMBERI KÖRNYEZET" WHERE id_group=5499 and langcode='hu';
UPDATE `concept_group` SET description="FIZIKAI VONATKOZÁSOK, ZAJ, REZGÉSEK, SUGÁRZÁSOK" WHERE id_group=6237 and langcode='hu';
UPDATE `concept_group` SET description="KIKAPCSOLÓDÁS, TURIZMUS" WHERE id_group=7007 and langcode='hu';
UPDATE `concept_group` SET description="KUTATÁS, TUDOMÁNYOK" WHERE id_group=7136 and langcode='hu';
UPDATE `concept_group` SET description="KOCKÁZATOK, BIZTONSÁG" WHERE id_group=7243 and langcode='hu';
UPDATE `concept_group` SET description="TÁRSADALOM" WHERE id_group=7779 and langcode='hu';
UPDATE `concept_group` SET description="ŰR/TÉR" WHERE id_group=7956 and langcode='hu';
UPDATE `concept_group` SET description="KERESKEDELEM, SZOLGÁLTATÁSOK" WHERE id_group=8575 and langcode='hu';
UPDATE `concept_group` SET description="FORGALOM, KÖZLEKEDÉS" WHERE id_group=8603 and langcode='hu';
UPDATE `concept_group` SET description="HULLADÉKOK, SZENNYEZŐANYAGOK, SZENNYEZÉS" WHERE id_group=9117 and langcode='hu';
UPDATE `concept_group` SET description="KÖRNYEZET (természeti környezet, emberi környezet)" WHERE id_group=10111 and langcode='hu';
UPDATE `concept_group` SET description="TERMÉKEK, ANYAGOK" WHERE id_group=10112 and langcode='hu';
UPDATE `concept_group` SET description="KÖVETKEZMÉNYEK, HATÁSOK" WHERE id_group=10114 and langcode='hu';
UPDATE `concept_group` SET description="ÁLTALÁNOS KIFEJEZÉSEK" WHERE id_group=10117 and langcode='hu';
UPDATE `concept_group` SET description="ERŐFORRÁSOK (erőforrások hasznosítása)" WHERE id_group=10118 and langcode='hu';
UPDATE `concept_group` SET description="KÖRNYEZETPOLITIKA" WHERE id_group=13109 and langcode='hu';
UPDATE `concept_group` SET description="IDŐ (kronológia)" WHERE id_group=14979 and langcode='hu';
UPDATE `concept_group` SET description="FUNKCIONÁLIS KIFEJEZÉSEK" WHERE id_group=14980 and langcode='hu';