UPDATE `theme` SET description="igazgatás" WHERE langcode='hu' and id_theme=1;
UPDATE `theme` SET description="mezőgazdaság" WHERE langcode='hu' and id_theme=2;
UPDATE `theme` SET description="levegő" WHERE langcode='hu' and id_theme=3;
UPDATE `theme` SET description="biológia" WHERE langcode='hu' and id_theme=4;
UPDATE `theme` SET description="épület" WHERE langcode='hu' and id_theme=5;
UPDATE `theme` SET description="kémia/vegyészet" WHERE langcode='hu' and id_theme=6;
UPDATE `theme` SET description="éghajlat" WHERE langcode='hu' and id_theme=7;
UPDATE `theme` SET description="természetdinamika" WHERE langcode='hu' and id_theme=8;
UPDATE `theme` SET description="közgazdaságtan" WHERE langcode='hu' and id_theme=9;
UPDATE `theme` SET description="energia" WHERE langcode='hu' and id_theme=10;
UPDATE `theme` SET description="környezetpolitika" WHERE langcode='hu' and id_theme=11;
UPDATE `theme` SET description="halászat" WHERE langcode='hu' and id_theme=12;
UPDATE `theme` SET description="étel, ívóvíz" WHERE langcode='hu' and id_theme=13;
UPDATE `theme` SET description="erdészet" WHERE langcode='hu' and id_theme=14;
UPDATE `theme` SET description="általános" WHERE langcode='hu' and id_theme=15;
UPDATE `theme` SET description="földrajz" WHERE langcode='hu' and id_theme=16;
UPDATE `theme` SET description="emberi egészség" WHERE langcode='hu' and id_theme=17;
UPDATE `theme` SET description="állattenyésztés" WHERE langcode='hu' and id_theme=18;
UPDATE `theme` SET description="ipar" WHERE langcode='hu' and id_theme=19;
UPDATE `theme` SET description="információ" WHERE langcode='hu' and id_theme=20;
UPDATE `theme` SET description="törvényhozás" WHERE langcode='hu' and id_theme=21;
UPDATE `theme` SET description="katonai vonatkozások" WHERE langcode='hu' and id_theme=22;
UPDATE `theme` SET description="természeti területek, táj, ökoszisztémák" WHERE langcode='hu' and id_theme=23;
UPDATE `theme` SET description="zaj, rezgések" WHERE langcode='hu' and id_theme=24;
UPDATE `theme` SET description="fizika" WHERE langcode='hu' and id_theme=25;
UPDATE `theme` SET description="szennyezés" WHERE langcode='hu' and id_theme=26;
UPDATE `theme` SET description="anyagok" WHERE langcode='hu' and id_theme=27;
UPDATE `theme` SET description="sugárzások" WHERE langcode='hu' and id_theme=28;
UPDATE `theme` SET description="turizmus" WHERE langcode='hu' and id_theme=29;
UPDATE `theme` SET description="kutatás" WHERE langcode='hu' and id_theme=30;
UPDATE `theme` SET description="erőforrások" WHERE langcode='hu' and id_theme=31;
UPDATE `theme` SET description="katasztrófák, balesetek, kockázatok" WHERE langcode='hu' and id_theme=32;
UPDATE `theme` SET description="kereskedelem, szolgáltatások" WHERE langcode='hu' and id_theme=33;
UPDATE `theme` SET description="társadalmi vonatkozások, lakosság" WHERE langcode='hu' and id_theme=34;
UPDATE `theme` SET description="talaj" WHERE langcode='hu' and id_theme=35;
UPDATE `theme` SET description="űr/tér" WHERE langcode='hu' and id_theme=36;
UPDATE `theme` SET description="közlekedés" WHERE langcode='hu' and id_theme=37;
UPDATE `theme` SET description="városi környezet, városi stressz" WHERE langcode='hu' and id_theme=38;
UPDATE `theme` SET description="hulladék" WHERE langcode='hu' and id_theme=39;
UPDATE `theme` SET description="víz" WHERE langcode='hu' and id_theme=40;