INSERT INTO property VALUES (2,2894,'ca','prefLabel',"ASPECTES SOCIALS, POLÍTICA AMBIENTAL, MESURES",0);
INSERT INTO property VALUES (2,4044,'ca','prefLabel',"ACTIVITATS HUMANES I PRODUCTES, EFECTES SOBRE EL MEDI AMBIENT",0);
INSERT INTO property VALUES (2,5306,'ca','prefLabel',"LLISTES ADDICIONALS",0);
INSERT INTO property VALUES (2,5499,'ca','prefLabel',"MEDI NATURAL, MEDI ANTRÒPIC",0);
INSERT INTO property VALUES (3,96,'ca','prefLabel',"ADMINISTRACIÓ, GESTIÓ, POLÍTICA, INSTITUCIONS, PLANIFICACIÓ",0);
INSERT INTO property VALUES (3,234,'ca','prefLabel',"AGRICULTURA, SILVICULTURA, CRIA D'ANIMALS, PESCA",0);
INSERT INTO property VALUES (3,618,'ca','prefLabel',"ATMOSFERA (aire, clima)",0);
INSERT INTO property VALUES (3,893,'ca','prefLabel',"BIOSFERA (organismes, ecosistemes)",0);
INSERT INTO property VALUES (3,1062,'ca','prefLabel',"ANTROPOSFERA (medi edificat, assentaments humans, ordenació del territori)",0);
INSERT INTO property VALUES (3,1349,'ca','prefLabel',"QUÍMICA, SUBSTÀNCIES, PROCESSOS",0);
INSERT INTO property VALUES (3,1922,'ca','prefLabel',"INFORMACIÓ, EDUCACIÓ, CULTURA, CONSCIÈNCIA AMBIENTAL",0);
INSERT INTO property VALUES (3,2504,'ca','prefLabel',"ECONOMIA, FINANCES",0);
INSERT INTO property VALUES (3,2711,'ca','prefLabel',"ENERGIA",0);
INSERT INTO property VALUES (3,3875,'ca','prefLabel',"SALUT, NUTRICIÓ",0);
INSERT INTO property VALUES (3,4125,'ca','prefLabel',"HIDROSFERA (aigua dolça, aigua marina, aigües)",0);
INSERT INTO property VALUES (3,4281,'ca','prefLabel',"INDÚSTRIA, ARTESANIA, TECNOLOGIA, EQUIPAMENTS",0);
INSERT INTO property VALUES (3,4630,'ca','prefLabel',"TERRITORI (paisatge, geografia)",0);
INSERT INTO property VALUES (3,4750,'ca','prefLabel',"LEGISLACIÓ, NORMES, CONVENCIONS",0);
INSERT INTO property VALUES (3,4856,'ca','prefLabel',"LITOSFERA (sòl, processos geològics)",0);
INSERT INTO property VALUES (3,6237,'ca','prefLabel',"ASPECTES FÍSICS, SOROLL, VIBRACIONS, RADIACIONS",0);
INSERT INTO property VALUES (3,7007,'ca','prefLabel',"RECREACIÓ, TURISME",0);
INSERT INTO property VALUES (3,7136,'ca','prefLabel',"INVESTIGACIÓ, CIÈNCIES",0);
INSERT INTO property VALUES (3,7243,'ca','prefLabel',"RISCOS, SEGURETAT",0);
INSERT INTO property VALUES (3,7779,'ca','prefLabel',"SOCIETAT",0);
INSERT INTO property VALUES (3,7956,'ca','prefLabel',"ESPAI",0);
INSERT INTO property VALUES (3,8575,'ca','prefLabel',"COMERÇ, SERVEIS",0);
INSERT INTO property VALUES (3,8603,'ca','prefLabel',"TRÀNSIT, TRANSPORT",0);
INSERT INTO property VALUES (3,9117,'ca','prefLabel',"RESIDUS, CONTAMINANTS, CONTAMINACIÓ",0);
INSERT INTO property VALUES (3,10111,'ca','prefLabel',"MEDI AMBIENT (medi natural, medi antròpic)",0);
INSERT INTO property VALUES (3,10112,'ca','prefLabel',"PRODUCTES MATERIALS",0);
INSERT INTO property VALUES (3,10114,'ca','prefLabel',"EFECTES, IMPACTES",0);
INSERT INTO property VALUES (3,10117,'ca','prefLabel',"TERMES GENERALS",0);
INSERT INTO property VALUES (3,10118,'ca','prefLabel',"RECURSOS (ús dels recursos)",0);
INSERT INTO property VALUES (3,13109,'ca','prefLabel',"POLÍTICA AMBIENTAL",0);
INSERT INTO property VALUES (3,14979,'ca','prefLabel',"TEMPS (cronologia) ",0);
INSERT INTO property VALUES (3,14980,'ca','prefLabel',"TERMES FUNCIONALS",0);
INSERT INTO property VALUES (4,1,'ca','prefLabel',"administració",0);
INSERT INTO property VALUES (4,2,'ca','prefLabel',"agricultura",0);
INSERT INTO property VALUES (4,3,'ca','prefLabel',"aire",0);
INSERT INTO property VALUES (4,4,'ca','prefLabel',"biologia",0);
INSERT INTO property VALUES (4,5,'ca','prefLabel',"edificació",0);
INSERT INTO property VALUES (4,6,'ca','prefLabel',"química",0);
INSERT INTO property VALUES (4,7,'ca','prefLabel',"clima",0);
INSERT INTO property VALUES (4,8,'ca','prefLabel',"dinàmica natural",0);
INSERT INTO property VALUES (4,9,'ca','prefLabel',"economia",0);
INSERT INTO property VALUES (4,10,'ca','prefLabel',"energia",0);
INSERT INTO property VALUES (4,11,'ca','prefLabel',"política ambiental",0);
INSERT INTO property VALUES (4,12,'ca','prefLabel',"pesca",0);
INSERT INTO property VALUES (4,13,'ca','prefLabel',"aliment, aigua potable",0);
INSERT INTO property VALUES (4,14,'ca','prefLabel',"silvicultura",0);
INSERT INTO property VALUES (4,15,'ca','prefLabel',"general",0);
INSERT INTO property VALUES (4,16,'ca','prefLabel',"geografia",0);
INSERT INTO property VALUES (4,17,'ca','prefLabel',"salut humana",0);
INSERT INTO property VALUES (4,18,'ca','prefLabel',"cria d'animals",0);
INSERT INTO property VALUES (4,19,'ca','prefLabel',"indústria",0);
INSERT INTO property VALUES (4,20,'ca','prefLabel',"informació",0);
INSERT INTO property VALUES (4,21,'ca','prefLabel',"legislació",0);
INSERT INTO property VALUES (4,22,'ca','prefLabel',"aspectes militars",0);
INSERT INTO property VALUES (4,23,'ca','prefLabel',"àrees naturals, paisatge, ecosistemes",0);
INSERT INTO property VALUES (4,24,'ca','prefLabel',"soroll, vibracions",0);
INSERT INTO property VALUES (4,25,'ca','prefLabel',"física",0);
INSERT INTO property VALUES (4,26,'ca','prefLabel',"contaminació",0);
INSERT INTO property VALUES (4,27,'ca','prefLabel',"materials",0);
INSERT INTO property VALUES (4,28,'ca','prefLabel',"radiacions",0);
INSERT INTO property VALUES (4,29,'ca','prefLabel',"turisme",0);
INSERT INTO property VALUES (4,30,'ca','prefLabel',"investigació",0);
INSERT INTO property VALUES (4,31,'ca','prefLabel',"recursos",0);
INSERT INTO property VALUES (4,32,'ca','prefLabel',"desastres, accidents, riscos",0);
INSERT INTO property VALUES (4,33,'ca','prefLabel',"comerç, serveis",0);
INSERT INTO property VALUES (4,34,'ca','prefLabel',"aspectes socials, població",0);
INSERT INTO property VALUES (4,35,'ca','prefLabel',"sòl",0);
INSERT INTO property VALUES (4,36,'ca','prefLabel',"espai",0);
INSERT INTO property VALUES (4,37,'ca','prefLabel',"transports",0);
INSERT INTO property VALUES (4,38,'ca','prefLabel',"medi ambient urbà, tensió urbana (estrès urbà)",0);
INSERT INTO property VALUES (4,39,'ca','prefLabel',"residu",0);
INSERT INTO property VALUES (4,40,'ca','prefLabel',"aigua",0);
